
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package com.pseudorygium.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.SpawnEggItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import java.util.function.Function;

import com.pseudorygium.item.TomatoSeedsItem;
import com.pseudorygium.item.TomatoItem;
import com.pseudorygium.item.SunflowerSeedsItem;
import com.pseudorygium.item.StrawberryItem;
import com.pseudorygium.item.SilverNuggetItem;
import com.pseudorygium.item.SilverIngotItem;
import com.pseudorygium.item.SapBottleItem;
import com.pseudorygium.item.RawVenisonItem;
import com.pseudorygium.item.RawTurkeyItem;
import com.pseudorygium.item.RawSilverItem;
import com.pseudorygium.item.RawQuailItem;
import com.pseudorygium.item.RawPheasantItem;
import com.pseudorygium.item.RawChevonItem;
import com.pseudorygium.item.RawCarpItem;
import com.pseudorygium.item.QuicksandBucketItem;
import com.pseudorygium.item.PeatItem;
import com.pseudorygium.item.OrangeItem;
import com.pseudorygium.item.OpenCoconutItem;
import com.pseudorygium.item.NetheriteKatanaItem;
import com.pseudorygium.item.MorinKhuurItem;
import com.pseudorygium.item.MapleSyrupBottleItem;
import com.pseudorygium.item.MaizeSeedsItem;
import com.pseudorygium.item.MaizeItem;
import com.pseudorygium.item.LemmingHideItem;
import com.pseudorygium.item.LeafItem;
import com.pseudorygium.item.LeafCrownItem;
import com.pseudorygium.item.LardItem;
import com.pseudorygium.item.KatanaItem;
import com.pseudorygium.item.HazelnutItem;
import com.pseudorygium.item.EarthwormItem;
import com.pseudorygium.item.CrabClawItem;
import com.pseudorygium.item.CookedVenisonItem;
import com.pseudorygium.item.CookedTurkeyItem;
import com.pseudorygium.item.CookedQuailItem;
import com.pseudorygium.item.CookedPheasantItem;
import com.pseudorygium.item.CookedChevonItem;
import com.pseudorygium.item.CookedCarpItem;
import com.pseudorygium.item.CobaltSwordItem;
import com.pseudorygium.item.CobaltShovelItem;
import com.pseudorygium.item.CobaltPickaxeItem;
import com.pseudorygium.item.CobaltIngotItem;
import com.pseudorygium.item.CobaltHoeItem;
import com.pseudorygium.item.CobaltAxeItem;
import com.pseudorygium.item.CobaltArmorItem;
import com.pseudorygium.item.CarpBucketItem;
import com.pseudorygium.item.BoomerangItem;
import com.pseudorygium.item.BananaItem;
import com.pseudorygium.PseudorygiumMod;

public class PseudorygiumModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(PseudorygiumMod.MODID);
	public static final DeferredItem<Item> ZEBRA_SPAWN_EGG = register("zebra_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.ZEBRA.get(), properties));
	public static final DeferredItem<Item> ECHIDNA_SPAWN_EGG = register("echidna_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.ECHIDNA.get(), properties));
	public static final DeferredItem<Item> BROWN_BEAR_SPAWN_EGG = register("brown_bear_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.BROWN_BEAR.get(), properties));
	public static final DeferredItem<Item> HEDGEHOG_SPAWN_EGG = register("hedgehog_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.HEDGEHOG.get(), properties));
	public static final DeferredItem<Item> DEER_SPAWN_EGG = register("deer_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.DEER.get(), properties));
	public static final DeferredItem<Item> HORNBEAM_WOOD = block(PseudorygiumModBlocks.HORNBEAM_WOOD);
	public static final DeferredItem<Item> HORNBEAM_LOG = block(PseudorygiumModBlocks.HORNBEAM_LOG);
	public static final DeferredItem<Item> HORNBEAM_PLANKS = block(PseudorygiumModBlocks.HORNBEAM_PLANKS);
	public static final DeferredItem<Item> HORNBEAM_LEAVES = block(PseudorygiumModBlocks.HORNBEAM_LEAVES);
	public static final DeferredItem<Item> HORNBEAM_STAIRS = block(PseudorygiumModBlocks.HORNBEAM_STAIRS);
	public static final DeferredItem<Item> HORNBEAM_SLAB = block(PseudorygiumModBlocks.HORNBEAM_SLAB);
	public static final DeferredItem<Item> HORNBEAM_FENCE = block(PseudorygiumModBlocks.HORNBEAM_FENCE);
	public static final DeferredItem<Item> HORNBEAM_FENCE_GATE = block(PseudorygiumModBlocks.HORNBEAM_FENCE_GATE);
	public static final DeferredItem<Item> HORNBEAM_PRESSURE_PLATE = block(PseudorygiumModBlocks.HORNBEAM_PRESSURE_PLATE);
	public static final DeferredItem<Item> HORNBEAM_BUTTON = block(PseudorygiumModBlocks.HORNBEAM_BUTTON);
	public static final DeferredItem<Item> SQUIRREL_SPAWN_EGG = register("squirrel_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SQUIRREL.get(), properties));
	public static final DeferredItem<Item> HORNBEAM_SAPLING = block(PseudorygiumModBlocks.HORNBEAM_SAPLING);
	public static final DeferredItem<Item> LINDEN_WOOD = block(PseudorygiumModBlocks.LINDEN_WOOD);
	public static final DeferredItem<Item> LINDEN_LOG = block(PseudorygiumModBlocks.LINDEN_LOG);
	public static final DeferredItem<Item> LINDEN_PLANKS = block(PseudorygiumModBlocks.LINDEN_PLANKS);
	public static final DeferredItem<Item> LINDEN_LEAVES = block(PseudorygiumModBlocks.LINDEN_LEAVES);
	public static final DeferredItem<Item> LINDEN_STAIRS = block(PseudorygiumModBlocks.LINDEN_STAIRS);
	public static final DeferredItem<Item> LINDEN_SLAB = block(PseudorygiumModBlocks.LINDEN_SLAB);
	public static final DeferredItem<Item> LINDEN_FENCE = block(PseudorygiumModBlocks.LINDEN_FENCE);
	public static final DeferredItem<Item> LINDEN_FENCE_GATE = block(PseudorygiumModBlocks.LINDEN_FENCE_GATE);
	public static final DeferredItem<Item> LINDEN_PRESSURE_PLATE = block(PseudorygiumModBlocks.LINDEN_PRESSURE_PLATE);
	public static final DeferredItem<Item> LINDEN_BUTTON = block(PseudorygiumModBlocks.LINDEN_BUTTON);
	public static final DeferredItem<Item> HORNBEAM_DOOR = doubleBlock(PseudorygiumModBlocks.HORNBEAM_DOOR);
	public static final DeferredItem<Item> GIRAFFE_SPAWN_EGG = register("giraffe_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.GIRAFFE.get(), properties));
	public static final DeferredItem<Item> PERMAFROST = block(PseudorygiumModBlocks.PERMAFROST);
	public static final DeferredItem<Item> MAMMOTH_SPAWN_EGG = register("mammoth_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.MAMMOTH.get(), properties));
	public static final DeferredItem<Item> PHEASANT_SPAWN_EGG = register("pheasant_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.PHEASANT.get(), properties));
	public static final DeferredItem<Item> PLATYPUS_SPAWN_EGG = register("platypus_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.PLATYPUS.get(), properties));
	public static final DeferredItem<Item> EARTHWORM = register("earthworm", EarthwormItem::new);
	public static final DeferredItem<Item> LION_SPAWN_EGG = register("lion_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.LION.get(), properties));
	public static final DeferredItem<Item> TIGER_SPAWN_EGG = register("tiger_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.TIGER.get(), properties));
	public static final DeferredItem<Item> BARRELEYE_SPAWN_EGG = register("barreleye_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.BARRELEYE.get(), properties));
	public static final DeferredItem<Item> ELEPHANT_SPAWN_EGG = register("elephant_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.ELEPHANT.get(), properties));
	public static final DeferredItem<Item> CRANE_SPAWN_EGG = register("crane_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CRANE.get(), properties));
	public static final DeferredItem<Item> SNAKE_SPAWN_EGG = register("snake_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SNAKE.get(), properties));
	public static final DeferredItem<Item> STORK_SPAWN_EGG = register("stork_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.STORK.get(), properties));
	public static final DeferredItem<Item> RAW_VENISON = register("raw_venison", RawVenisonItem::new);
	public static final DeferredItem<Item> COOKED_VENISON = register("cooked_venison", CookedVenisonItem::new);
	public static final DeferredItem<Item> LINDEN_DOOR = doubleBlock(PseudorygiumModBlocks.LINDEN_DOOR);
	public static final DeferredItem<Item> HORNBEAM_TRAPDOOR = block(PseudorygiumModBlocks.HORNBEAM_TRAPDOOR);
	public static final DeferredItem<Item> LINDEN_TRAPDOOR = block(PseudorygiumModBlocks.LINDEN_TRAPDOOR);
	public static final DeferredItem<Item> WOODPECKER_SPAWN_EGG = register("woodpecker_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.WOODPECKER.get(), properties));
	public static final DeferredItem<Item> LINDEN_SAPLING = block(PseudorygiumModBlocks.LINDEN_SAPLING);
	public static final DeferredItem<Item> PEAT_BLOCK = block(PseudorygiumModBlocks.PEAT_BLOCK);
	public static final DeferredItem<Item> WILLOW_WOOD = block(PseudorygiumModBlocks.WILLOW_WOOD);
	public static final DeferredItem<Item> WILLOW_LOG = block(PseudorygiumModBlocks.WILLOW_LOG);
	public static final DeferredItem<Item> WILLOW_PLANKS = block(PseudorygiumModBlocks.WILLOW_PLANKS);
	public static final DeferredItem<Item> WILLOW_LEAVES = block(PseudorygiumModBlocks.WILLOW_LEAVES);
	public static final DeferredItem<Item> WILLOW_STAIRS = block(PseudorygiumModBlocks.WILLOW_STAIRS);
	public static final DeferredItem<Item> WILLOW_SLAB = block(PseudorygiumModBlocks.WILLOW_SLAB);
	public static final DeferredItem<Item> WILLOW_FENCE = block(PseudorygiumModBlocks.WILLOW_FENCE);
	public static final DeferredItem<Item> WILLOW_FENCE_GATE = block(PseudorygiumModBlocks.WILLOW_FENCE_GATE);
	public static final DeferredItem<Item> WILLOW_PRESSURE_PLATE = block(PseudorygiumModBlocks.WILLOW_PRESSURE_PLATE);
	public static final DeferredItem<Item> WILLOW_BUTTON = block(PseudorygiumModBlocks.WILLOW_BUTTON);
	public static final DeferredItem<Item> BUFFALO_SPAWN_EGG = register("buffalo_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.BUFFALO.get(), properties));
	public static final DeferredItem<Item> WILLOW_SAPLING = block(PseudorygiumModBlocks.WILLOW_SAPLING);
	public static final DeferredItem<Item> PEAT = register("peat", PeatItem::new);
	public static final DeferredItem<Item> SITATUNGA_SPAWN_EGG = register("sitatunga_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SITATUNGA.get(), properties));
	public static final DeferredItem<Item> WILLOW_DOOR = doubleBlock(PseudorygiumModBlocks.WILLOW_DOOR);
	public static final DeferredItem<Item> WILLOW_TRAPDOOR = block(PseudorygiumModBlocks.WILLOW_TRAPDOOR);
	public static final DeferredItem<Item> FOSSA_SPAWN_EGG = register("fossa_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.FOSSA.get(), properties));
	public static final DeferredItem<Item> CHAMOIS_SPAWN_EGG = register("chamois_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CHAMOIS.get(), properties));
	public static final DeferredItem<Item> SNAIL_SPAWN_EGG = register("snail_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SNAIL.get(), properties));
	public static final DeferredItem<Item> SNOW_LEOPARD_SPAWN_EGG = register("snow_leopard_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SNOW_LEOPARD.get(), properties));
	public static final DeferredItem<Item> CHIMPANZEE_SPAWN_EGG = register("chimpanzee_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CHIMPANZEE.get(), properties));
	public static final DeferredItem<Item> ORANGE = register("orange", OrangeItem::new);
	public static final DeferredItem<Item> BANANA = register("banana", BananaItem::new);
	public static final DeferredItem<Item> AYE_AYE_SPAWN_EGG = register("aye_aye_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.AYE_AYE.get(), properties));
	public static final DeferredItem<Item> HAZELNUT = register("hazelnut", HazelnutItem::new);
	public static final DeferredItem<Item> CAPYBARA_SPAWN_EGG = register("capybara_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CAPYBARA.get(), properties));
	public static final DeferredItem<Item> SAIGA_SPAWN_EGG = register("saiga_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SAIGA.get(), properties));
	public static final DeferredItem<Item> MONKEY_SPAWN_EGG = register("monkey_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.MONKEY.get(), properties));
	public static final DeferredItem<Item> RAW_PHEASANT = register("raw_pheasant", RawPheasantItem::new);
	public static final DeferredItem<Item> COOKED_PHEASANT = register("cooked_pheasant", CookedPheasantItem::new);
	public static final DeferredItem<Item> MANTIS_SPAWN_EGG = register("mantis_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.MANTIS.get(), properties));
	public static final DeferredItem<Item> OSTRICH_SPAWN_EGG = register("ostrich_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.OSTRICH.get(), properties));
	public static final DeferredItem<Item> SEAL_SPAWN_EGG = register("seal_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SEAL.get(), properties));
	public static final DeferredItem<Item> REINDEER_SPAWN_EGG = register("reindeer_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.REINDEER.get(), properties));
	public static final DeferredItem<Item> LEMMING_SPAWN_EGG = register("lemming_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.LEMMING.get(), properties));
	public static final DeferredItem<Item> GAZELLE_SPAWN_EGG = register("gazelle_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.GAZELLE.get(), properties));
	public static final DeferredItem<Item> CHEETAH_SPAWN_EGG = register("cheetah_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CHEETAH.get(), properties));
	public static final DeferredItem<Item> HUMMINGBIRD_SPAWN_EGG = register("hummingbird_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.HUMMINGBIRD.get(), properties));
	public static final DeferredItem<Item> VENUS_FLYTRAP = block(PseudorygiumModBlocks.VENUS_FLYTRAP);
	public static final DeferredItem<Item> LEMMING_HIDE = register("lemming_hide", LemmingHideItem::new);
	public static final DeferredItem<Item> SECRETARYBIRD_SPAWN_EGG = register("secretarybird_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SECRETARYBIRD.get(), properties));
	public static final DeferredItem<Item> RAW_CHEVON = register("raw_chevon", RawChevonItem::new);
	public static final DeferredItem<Item> COOKED_CHEVON = register("cooked_chevon", CookedChevonItem::new);
	public static final DeferredItem<Item> MOOSE_SPAWN_EGG = register("moose_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.MOOSE.get(), properties));
	public static final DeferredItem<Item> RED_PANDA_SPAWN_EGG = register("red_panda_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.RED_PANDA.get(), properties));
	public static final DeferredItem<Item> RACCOON_SPAWN_EGG = register("raccoon_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.RACCOON.get(), properties));
	public static final DeferredItem<Item> SLOTH_SPAWN_EGG = register("sloth_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SLOTH.get(), properties));
	public static final DeferredItem<Item> BINTURONG_SPAWN_EGG = register("binturong_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.BINTURONG.get(), properties));
	public static final DeferredItem<Item> BADGER_SPAWN_EGG = register("badger_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.BADGER.get(), properties));
	public static final DeferredItem<Item> HERON_SPAWN_EGG = register("heron_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.HERON.get(), properties));
	public static final DeferredItem<Item> CRAB_SPAWN_EGG = register("crab_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CRAB.get(), properties));
	public static final DeferredItem<Item> TORTOISE_SPAWN_EGG = register("tortoise_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.TORTOISE.get(), properties));
	public static final DeferredItem<Item> OKAPI_SPAWN_EGG = register("okapi_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.OKAPI.get(), properties));
	public static final DeferredItem<Item> TANUKI_SPAWN_EGG = register("tanuki_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.TANUKI.get(), properties));
	public static final DeferredItem<Item> CRAB_CLAW = register("crab_claw", CrabClawItem::new);
	public static final DeferredItem<Item> KANGAROO_SPAWN_EGG = register("kangaroo_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.KANGAROO.get(), properties));
	public static final DeferredItem<Item> OUTBACK_BUSH = block(PseudorygiumModBlocks.OUTBACK_BUSH);
	public static final DeferredItem<Item> GHARIAL_SPAWN_EGG = register("gharial_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.GHARIAL.get(), properties));
	public static final DeferredItem<Item> ORANGUTAN_SPAWN_EGG = register("orangutan_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.ORANGUTAN.get(), properties));
	public static final DeferredItem<Item> LOPHORINA_SPAWN_EGG = register("lophorina_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.LOPHORINA.get(), properties));
	public static final DeferredItem<Item> AARDVARK_SPAWN_EGG = register("aardvark_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.AARDVARK.get(), properties));
	public static final DeferredItem<Item> PANGOLIN_SPAWN_EGG = register("pangolin_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.PANGOLIN.get(), properties));
	public static final DeferredItem<Item> BUTTERFLY_SPAWN_EGG = register("butterfly_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.BUTTERFLY.get(), properties));
	public static final DeferredItem<Item> MAGPIE_SPAWN_EGG = register("magpie_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.MAGPIE.get(), properties));
	public static final DeferredItem<Item> HIPPOPOTAMUS_SPAWN_EGG = register("hippopotamus_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.HIPPOPOTAMUS.get(), properties));
	public static final DeferredItem<Item> TITMOUSE_SPAWN_EGG = register("titmouse_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.TITMOUSE.get(), properties));
	public static final DeferredItem<Item> SPARROW_SPAWN_EGG = register("sparrow_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SPARROW.get(), properties));
	public static final DeferredItem<Item> ROBIN_SPAWN_EGG = register("robin_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.ROBIN.get(), properties));
	public static final DeferredItem<Item> CHAFFINCH_SPAWN_EGG = register("chaffinch_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CHAFFINCH.get(), properties));
	public static final DeferredItem<Item> BULLFINCH_SPAWN_EGG = register("bullfinch_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.BULLFINCH.get(), properties));
	public static final DeferredItem<Item> KIWI_SPAWN_EGG = register("kiwi_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.KIWI.get(), properties));
	public static final DeferredItem<Item> CROW_SPAWN_EGG = register("crow_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CROW.get(), properties));
	public static final DeferredItem<Item> RAVEN_SPAWN_EGG = register("raven_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.RAVEN.get(), properties));
	public static final DeferredItem<Item> JAY_SPAWN_EGG = register("jay_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.JAY.get(), properties));
	public static final DeferredItem<Item> RHINOCEROS_SPAWN_EGG = register("rhinoceros_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.RHINOCEROS.get(), properties));
	public static final DeferredItem<Item> WATERBUCK_SPAWN_EGG = register("waterbuck_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.WATERBUCK.get(), properties));
	public static final DeferredItem<Item> PENGUIN_SPAWN_EGG = register("penguin_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.PENGUIN.get(), properties));
	public static final DeferredItem<Item> PEAFOWL_SPAWN_EGG = register("peafowl_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.PEAFOWL.get(), properties));
	public static final DeferredItem<Item> WALRUS_SPAWN_EGG = register("walrus_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.WALRUS.get(), properties));
	public static final DeferredItem<Item> MEERKAT_SPAWN_EGG = register("meerkat_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.MEERKAT.get(), properties));
	public static final DeferredItem<Item> VULTURE_SPAWN_EGG = register("vulture_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.VULTURE.get(), properties));
	public static final DeferredItem<Item> PIGEON_SPAWN_EGG = register("pigeon_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.PIGEON.get(), properties));
	public static final DeferredItem<Item> BELLBIRD_SPAWN_EGG = register("bellbird_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.BELLBIRD.get(), properties));
	public static final DeferredItem<Item> LARD = register("lard", LardItem::new);
	public static final DeferredItem<Item> LEMUR_SPAWN_EGG = register("lemur_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.LEMUR.get(), properties));
	public static final DeferredItem<Item> LEAF = register("leaf", LeafItem::new);
	public static final DeferredItem<Item> LEAF_CROWN_HELMET = register("leaf_crown_helmet", LeafCrownItem.Helmet::new);
	public static final DeferredItem<Item> ZORSE_SPAWN_EGG = register("zorse_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.ZORSE.get(), properties));
	public static final DeferredItem<Item> ZONKEY_SPAWN_EGG = register("zonkey_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.ZONKEY.get(), properties));
	public static final DeferredItem<Item> GORILLA_SPAWN_EGG = register("gorilla_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.GORILLA.get(), properties));
	public static final DeferredItem<Item> MOUSE_LEMUR_SPAWN_EGG = register("mouse_lemur_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.MOUSE_LEMUR.get(), properties));
	public static final DeferredItem<Item> STRIPPED_HORMBEAM_LOG = block(PseudorygiumModBlocks.STRIPPED_HORMBEAM_LOG);
	public static final DeferredItem<Item> STRIPPED_HORNBEAM_WOOD = block(PseudorygiumModBlocks.STRIPPED_HORNBEAM_WOOD);
	public static final DeferredItem<Item> STRIPPED_WILLOW_LOG = block(PseudorygiumModBlocks.STRIPPED_WILLOW_LOG);
	public static final DeferredItem<Item> STRIPPED_WILLOW_WOOD = block(PseudorygiumModBlocks.STRIPPED_WILLOW_WOOD);
	public static final DeferredItem<Item> STRIPPED_LINDEN_WOOD = block(PseudorygiumModBlocks.STRIPPED_LINDEN_WOOD);
	public static final DeferredItem<Item> STRIPPED_LINDEN_LOG = block(PseudorygiumModBlocks.STRIPPED_LINDEN_LOG);
	public static final DeferredItem<Item> GIBBON_SPAWN_EGG = register("gibbon_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.GIBBON.get(), properties));
	public static final DeferredItem<Item> EMU_SPAWN_EGG = register("emu_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.EMU.get(), properties));
	public static final DeferredItem<Item> QUOLL_SPAWN_EGG = register("quoll_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.QUOLL.get(), properties));
	public static final DeferredItem<Item> WOMBAT_SPAWN_EGG = register("wombat_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.WOMBAT.get(), properties));
	public static final DeferredItem<Item> BANDICOOT_SPAWN_EGG = register("bandicoot_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.BANDICOOT.get(), properties));
	public static final DeferredItem<Item> NUMBAT_SPAWN_EGG = register("numbat_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.NUMBAT.get(), properties));
	public static final DeferredItem<Item> POPLAR_WOOD = block(PseudorygiumModBlocks.POPLAR_WOOD);
	public static final DeferredItem<Item> POPLAR_LOG = block(PseudorygiumModBlocks.POPLAR_LOG);
	public static final DeferredItem<Item> POPLAR_PLANKS = block(PseudorygiumModBlocks.POPLAR_PLANKS);
	public static final DeferredItem<Item> POPLAR_LEAVES = block(PseudorygiumModBlocks.POPLAR_LEAVES);
	public static final DeferredItem<Item> POPLAR_STAIRS = block(PseudorygiumModBlocks.POPLAR_STAIRS);
	public static final DeferredItem<Item> POPLAR_SLAB = block(PseudorygiumModBlocks.POPLAR_SLAB);
	public static final DeferredItem<Item> POPLAR_FENCE = block(PseudorygiumModBlocks.POPLAR_FENCE);
	public static final DeferredItem<Item> POPLAR_FENCE_GATE = block(PseudorygiumModBlocks.POPLAR_FENCE_GATE);
	public static final DeferredItem<Item> POPLAR_PRESSURE_PLATE = block(PseudorygiumModBlocks.POPLAR_PRESSURE_PLATE);
	public static final DeferredItem<Item> POPLAR_BUTTON = block(PseudorygiumModBlocks.POPLAR_BUTTON);
	public static final DeferredItem<Item> STRIPPED_POPLAR_WOOD = block(PseudorygiumModBlocks.STRIPPED_POPLAR_WOOD);
	public static final DeferredItem<Item> STRIPPED_POPLAR_LOG = block(PseudorygiumModBlocks.STRIPPED_POPLAR_LOG);
	public static final DeferredItem<Item> POPLAR_DOOR = doubleBlock(PseudorygiumModBlocks.POPLAR_DOOR);
	public static final DeferredItem<Item> POPLAR_TRAPDOOR = block(PseudorygiumModBlocks.POPLAR_TRAPDOOR);
	public static final DeferredItem<Item> POPLAR_SAPLING = block(PseudorygiumModBlocks.POPLAR_SAPLING);
	public static final DeferredItem<Item> SUNFLOWER_SEEDS = register("sunflower_seeds", SunflowerSeedsItem::new);
	public static final DeferredItem<Item> HAMSTER_SPAWN_EGG = register("hamster_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.HAMSTER.get(), properties));
	public static final DeferredItem<Item> LYNX_SPAWN_EGG = register("lynx_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.LYNX.get(), properties));
	public static final DeferredItem<Item> BACTRIAN_CAMEL_SPAWN_EGG = register("bactrian_camel_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.BACTRIAN_CAMEL.get(), properties));
	public static final DeferredItem<Item> PHILIPPINE_EAGLE_SPAWN_EGG = register("philippine_eagle_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.PHILIPPINE_EAGLE.get(), properties));
	public static final DeferredItem<Item> EAGLE_SPAWN_EGG = register("eagle_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.EAGLE.get(), properties));
	public static final DeferredItem<Item> OSPREY_SPAWN_EGG = register("osprey_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.OSPREY.get(), properties));
	public static final DeferredItem<Item> MOUSE_SPAWN_EGG = register("mouse_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.MOUSE.get(), properties));
	public static final DeferredItem<Item> OWL_SPAWN_EGG = register("owl_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.OWL.get(), properties));
	public static final DeferredItem<Item> SNOWY_OWL_SPAWN_EGG = register("snowy_owl_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SNOWY_OWL.get(), properties));
	public static final DeferredItem<Item> PTARMIGAN_SPAWN_EGG = register("ptarmigan_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.PTARMIGAN.get(), properties));
	public static final DeferredItem<Item> HOATZIN_SPAWN_EGG = register("hoatzin_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.HOATZIN.get(), properties));
	public static final DeferredItem<Item> COLD_DESERT_GRASS = block(PseudorygiumModBlocks.COLD_DESERT_GRASS);
	public static final DeferredItem<Item> CAMELTHORN = block(PseudorygiumModBlocks.CAMELTHORN);
	public static final DeferredItem<Item> COLD_DESERT_DIRT = block(PseudorygiumModBlocks.COLD_DESERT_DIRT);
	public static final DeferredItem<Item> DUIKER_SPAWN_EGG = register("duiker_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.DUIKER.get(), properties));
	public static final DeferredItem<Item> WARTHOG_SPAWN_EGG = register("warthog_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.WARTHOG.get(), properties));
	public static final DeferredItem<Item> BAOBAB_WOOD = block(PseudorygiumModBlocks.BAOBAB_WOOD);
	public static final DeferredItem<Item> BAOBAB_LOG = block(PseudorygiumModBlocks.BAOBAB_LOG);
	public static final DeferredItem<Item> BAOBAB_PLANKS = block(PseudorygiumModBlocks.BAOBAB_PLANKS);
	public static final DeferredItem<Item> BAOBAB_LEAVES = block(PseudorygiumModBlocks.BAOBAB_LEAVES);
	public static final DeferredItem<Item> BAOBAB_STAIRS = block(PseudorygiumModBlocks.BAOBAB_STAIRS);
	public static final DeferredItem<Item> BAOBAB_SLAB = block(PseudorygiumModBlocks.BAOBAB_SLAB);
	public static final DeferredItem<Item> BAOBAB_FENCE = block(PseudorygiumModBlocks.BAOBAB_FENCE);
	public static final DeferredItem<Item> BAOBAB_FENCE_GATE = block(PseudorygiumModBlocks.BAOBAB_FENCE_GATE);
	public static final DeferredItem<Item> BAOBAB_PRESSURE_PLATE = block(PseudorygiumModBlocks.BAOBAB_PRESSURE_PLATE);
	public static final DeferredItem<Item> BAOBAB_BUTTON = block(PseudorygiumModBlocks.BAOBAB_BUTTON);
	public static final DeferredItem<Item> BAOBAB_DOOR = doubleBlock(PseudorygiumModBlocks.BAOBAB_DOOR);
	public static final DeferredItem<Item> BAOBAB_TRAPDOOR = block(PseudorygiumModBlocks.BAOBAB_TRAPDOOR);
	public static final DeferredItem<Item> STRIPPED_BAOBAB_WOOD = block(PseudorygiumModBlocks.STRIPPED_BAOBAB_WOOD);
	public static final DeferredItem<Item> STRIPPED_BAOBAB_LOG = block(PseudorygiumModBlocks.STRIPPED_BAOBAB_LOG);
	public static final DeferredItem<Item> BAOBAB_SAPLING = block(PseudorygiumModBlocks.BAOBAB_SAPLING);
	public static final DeferredItem<Item> CHIRU_SPAWN_EGG = register("chiru_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CHIRU.get(), properties));
	public static final DeferredItem<Item> HONEY_BADGER_SPAWN_EGG = register("honey_badger_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.HONEY_BADGER.get(), properties));
	public static final DeferredItem<Item> MOHO_SPAWN_EGG = register("moho_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.MOHO.get(), properties));
	public static final DeferredItem<Item> BONGO_SPAWN_EGG = register("bongo_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.BONGO.get(), properties));
	public static final DeferredItem<Item> CATERPILLAR_SPAWN_EGG = register("caterpillar_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CATERPILLAR.get(), properties));
	public static final DeferredItem<Item> OCTOPUS_SPAWN_EGG = register("octopus_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.OCTOPUS.get(), properties));
	public static final DeferredItem<Item> APHID_SPAWN_EGG = register("aphid_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.APHID.get(), properties));
	public static final DeferredItem<Item> JUMPING_SPIDER_SPAWN_EGG = register("jumping_spider_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.JUMPING_SPIDER.get(), properties));
	public static final DeferredItem<Item> LADYBUG_SPAWN_EGG = register("ladybug_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.LADYBUG.get(), properties));
	public static final DeferredItem<Item> EARTHWORM_ENTITY_SPAWN_EGG = register("earthworm_entity_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.EARTHWORM_ENTITY.get(), properties));
	public static final DeferredItem<Item> SHELTOPUSIK_SPAWN_EGG = register("sheltopusik_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SHELTOPUSIK.get(), properties));
	public static final DeferredItem<Item> ANTHILL = block(PseudorygiumModBlocks.ANTHILL);
	public static final DeferredItem<Item> ANT_SPAWN_EGG = register("ant_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.ANT.get(), properties));
	public static final DeferredItem<Item> KOMODO_DRAGON_SPAWN_EGG = register("komodo_dragon_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.KOMODO_DRAGON.get(), properties));
	public static final DeferredItem<Item> SALAMANDER_SPAWN_EGG = register("salamander_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SALAMANDER.get(), properties));
	public static final DeferredItem<Item> LIZARD_SPAWN_EGG = register("lizard_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.LIZARD.get(), properties));
	public static final DeferredItem<Item> IGUANA_SPAWN_EGG = register("iguana_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.IGUANA.get(), properties));
	public static final DeferredItem<Item> SERVAL_SPAWN_EGG = register("serval_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SERVAL.get(), properties));
	public static final DeferredItem<Item> PORCUPINE_SPAWN_EGG = register("porcupine_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.PORCUPINE.get(), properties));
	public static final DeferredItem<Item> MARABOU_SPAWN_EGG = register("marabou_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.MARABOU.get(), properties));
	public static final DeferredItem<Item> ORYX_SPAWN_EGG = register("oryx_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.ORYX.get(), properties));
	public static final DeferredItem<Item> AARDWOLF_SPAWN_EGG = register("aardwolf_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.AARDWOLF.get(), properties));
	public static final DeferredItem<Item> GERENUK_SPAWN_EGG = register("gerenuk_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.GERENUK.get(), properties));
	public static final DeferredItem<Item> HYENA_SPAWN_EGG = register("hyena_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.HYENA.get(), properties));
	public static final DeferredItem<Item> CROCODILE_SPAWN_EGG = register("crocodile_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CROCODILE.get(), properties));
	public static final DeferredItem<Item> FOREST_BUFFALO_SPAWN_EGG = register("forest_buffalo_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.FOREST_BUFFALO.get(), properties));
	public static final DeferredItem<Item> FENNEC_FOX_SPAWN_EGG = register("fennec_fox_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.FENNEC_FOX.get(), properties));
	public static final DeferredItem<Item> KAKAPO_SPAWN_EGG = register("kakapo_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.KAKAPO.get(), properties));
	public static final DeferredItem<Item> KAGU_SPAWN_EGG = register("kagu_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.KAGU.get(), properties));
	public static final DeferredItem<Item> RAT_SPAWN_EGG = register("rat_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.RAT.get(), properties));
	public static final DeferredItem<Item> BEE_EATER_SPAWN_EGG = register("bee_eater_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.BEE_EATER.get(), properties));
	public static final DeferredItem<Item> BIRD_OF_PARADISE_SPAWN_EGG = register("bird_of_paradise_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.BIRD_OF_PARADISE.get(), properties));
	public static final DeferredItem<Item> CASSOWARY_SPAWN_EGG = register("cassowary_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CASSOWARY.get(), properties));
	public static final DeferredItem<Item> TOUCAN_SPAWN_EGG = register("toucan_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.TOUCAN.get(), properties));
	public static final DeferredItem<Item> GREBE_SPAWN_EGG = register("grebe_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.GREBE.get(), properties));
	public static final DeferredItem<Item> RHEA_SPAWN_EGG = register("rhea_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.RHEA.get(), properties));
	public static final DeferredItem<Item> DUCK_SPAWN_EGG = register("duck_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.DUCK.get(), properties));
	public static final DeferredItem<Item> MANDARIN_DUCK_SPAWN_EGG = register("mandarin_duck_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.MANDARIN_DUCK.get(), properties));
	public static final DeferredItem<Item> JUNGLEFOWL_SPAWN_EGG = register("junglefowl_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.JUNGLEFOWL.get(), properties));
	public static final DeferredItem<Item> HORNBILL_SPAWN_EGG = register("hornbill_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.HORNBILL.get(), properties));
	public static final DeferredItem<Item> FRIGATEBIRD_SPAWN_EGG = register("frigatebird_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.FRIGATEBIRD.get(), properties));
	public static final DeferredItem<Item> SPOONBILL_SPAWN_EGG = register("spoonbill_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SPOONBILL.get(), properties));
	public static final DeferredItem<Item> FLAMINGO_SPAWN_EGG = register("flamingo_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.FLAMINGO.get(), properties));
	public static final DeferredItem<Item> SHOEBILL_SPAWN_EGG = register("shoebill_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SHOEBILL.get(), properties));
	public static final DeferredItem<Item> PRZEVALSKI_HORSE_SPAWN_EGG = register("przevalski_horse_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.PRZEVALSKI_HORSE.get(), properties));
	public static final DeferredItem<Item> DOMESTIC_GOAT_SPAWN_EGG = register("domestic_goat_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.DOMESTIC_GOAT.get(), properties));
	public static final DeferredItem<Item> GOLDFINCH_SPAWN_EGG = register("goldfinch_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.GOLDFINCH.get(), properties));
	public static final DeferredItem<Item> SHRIMP_SPAWN_EGG = register("shrimp_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SHRIMP.get(), properties));
	public static final DeferredItem<Item> YAK_SPAWN_EGG = register("yak_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.YAK.get(), properties));
	public static final DeferredItem<Item> IBIS_SPAWN_EGG = register("ibis_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.IBIS.get(), properties));
	public static final DeferredItem<Item> CRAYFISH_SPAWN_EGG = register("crayfish_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CRAYFISH.get(), properties));
	public static final DeferredItem<Item> FRUIT_BAT_SPAWN_EGG = register("fruit_bat_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.FRUIT_BAT.get(), properties));
	public static final DeferredItem<Item> PALLAS_CAT_SPAWN_EGG = register("pallas_cat_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.PALLAS_CAT.get(), properties));
	public static final DeferredItem<Item> JERBOA_SPAWN_EGG = register("jerboa_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.JERBOA.get(), properties));
	public static final DeferredItem<Item> ELEPHANT_SHREW_SPAWN_EGG = register("elephant_shrew_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.ELEPHANT_SHREW.get(), properties));
	public static final DeferredItem<Item> FORMICARIUM = block(PseudorygiumModBlocks.FORMICARIUM);
	public static final DeferredItem<Item> FERRET_SPAWN_EGG = register("ferret_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.FERRET.get(), properties));
	public static final DeferredItem<Item> POLECAT_SPAWN_EGG = register("polecat_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.POLECAT.get(), properties));
	public static final DeferredItem<Item> SPRINGHARE_SPAWN_EGG = register("springhare_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SPRINGHARE.get(), properties));
	public static final DeferredItem<Item> OTTER_SPAWN_EGG = register("otter_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.OTTER.get(), properties));
	public static final DeferredItem<Item> MARA_SPAWN_EGG = register("mara_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.MARA.get(), properties));
	public static final DeferredItem<Item> PUFFIN_SPAWN_EGG = register("puffin_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.PUFFIN.get(), properties));
	public static final DeferredItem<Item> MARMOT_SPAWN_EGG = register("marmot_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.MARMOT.get(), properties));
	public static final DeferredItem<Item> BLUE_WHALE_SPAWN_EGG = register("blue_whale_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.BLUE_WHALE.get(), properties));
	public static final DeferredItem<Item> ORCA_SPAWN_EGG = register("orca_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.ORCA.get(), properties));
	public static final DeferredItem<Item> BELUGA_WHALE_SPAWN_EGG = register("beluga_whale_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.BELUGA_WHALE.get(), properties));
	public static final DeferredItem<Item> BELUGA_STURGEON_SPAWN_EGG = register("beluga_sturgeon_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.BELUGA_STURGEON.get(), properties));
	public static final DeferredItem<Item> SEA_OTTER_SPAWN_EGG = register("sea_otter_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SEA_OTTER.get(), properties));
	public static final DeferredItem<Item> SEAGULL_SPAWN_EGG = register("seagull_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SEAGULL.get(), properties));
	public static final DeferredItem<Item> BOOBY_SPAWN_EGG = register("booby_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.BOOBY.get(), properties));
	public static final DeferredItem<Item> SAWFISH_SPAWN_EGG = register("sawfish_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SAWFISH.get(), properties));
	public static final DeferredItem<Item> WHITE_SHARK_SPAWN_EGG = register("white_shark_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.WHITE_SHARK.get(), properties));
	public static final DeferredItem<Item> PADDLEFISH_SPAWN_EGG = register("paddlefish_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.PADDLEFISH.get(), properties));
	public static final DeferredItem<Item> HUMPBACK_WHALE_SPAWN_EGG = register("humpback_whale_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.HUMPBACK_WHALE.get(), properties));
	public static final DeferredItem<Item> FIDDLER_CRAB_SPAWN_EGG = register("fiddler_crab_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.FIDDLER_CRAB.get(), properties));
	public static final DeferredItem<Item> SWAN_SPAWN_EGG = register("swan_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SWAN.get(), properties));
	public static final DeferredItem<Item> TARSIER_SPAWN_EGG = register("tarsier_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.TARSIER.get(), properties));
	public static final DeferredItem<Item> MANATEE_SPAWN_EGG = register("manatee_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.MANATEE.get(), properties));
	public static final DeferredItem<Item> PUMA_SPAWN_EGG = register("puma_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.PUMA.get(), properties));
	public static final DeferredItem<Item> CARACAL_SPAWN_EGG = register("caracal_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CARACAL.get(), properties));
	public static final DeferredItem<Item> CLOUDED_LEOPARD_SPAWN_EGG = register("clouded_leopard_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CLOUDED_LEOPARD.get(), properties));
	public static final DeferredItem<Item> ANTEATER_SPAWN_EGG = register("anteater_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.ANTEATER.get(), properties));
	public static final DeferredItem<Item> JAGUAR_SPAWN_EGG = register("jaguar_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.JAGUAR.get(), properties));
	public static final DeferredItem<Item> FLYING_SQUIRREL_SPAWN_EGG = register("flying_squirrel_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.FLYING_SQUIRREL.get(), properties));
	public static final DeferredItem<Item> SEAHORSE_SPAWN_EGG = register("seahorse_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SEAHORSE.get(), properties));
	public static final DeferredItem<Item> SEADRAGON_SPAWN_EGG = register("seadragon_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SEADRAGON.get(), properties));
	public static final DeferredItem<Item> SUGAR_GLIDER_SPAWN_EGG = register("sugar_glider_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SUGAR_GLIDER.get(), properties));
	public static final DeferredItem<Item> MOLE_SPAWN_EGG = register("mole_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.MOLE.get(), properties));
	public static final DeferredItem<Item> JELLYFISH_SPAWN_EGG = register("jellyfish_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.JELLYFISH.get(), properties));
	public static final DeferredItem<Item> DRAGONFLY_SPAWN_EGG = register("dragonfly_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.DRAGONFLY.get(), properties));
	public static final DeferredItem<Item> PROBOSCIS_MONKEY_SPAWN_EGG = register("proboscis_monkey_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.PROBOSCIS_MONKEY.get(), properties));
	public static final DeferredItem<Item> HAMADRYAS_BABOON_SPAWN_EGG = register("hamadryas_baboon_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.HAMADRYAS_BABOON.get(), properties));
	public static final DeferredItem<Item> CHACMA_BABOON_SPAWN_EGG = register("chacma_baboon_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CHACMA_BABOON.get(), properties));
	public static final DeferredItem<Item> OLIVE_BABOON_SPAWN_EGG = register("olive_baboon_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.OLIVE_BABOON.get(), properties));
	public static final DeferredItem<Item> SIAMANG_SPAWN_EGG = register("siamang_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SIAMANG.get(), properties));
	public static final DeferredItem<Item> STAG_BEETLE_SPAWN_EGG = register("stag_beetle_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.STAG_BEETLE.get(), properties));
	public static final DeferredItem<Item> GECKO_SPAWN_EGG = register("gecko_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.GECKO.get(), properties));
	public static final DeferredItem<Item> MANTIS_SHRIMP_SPAWN_EGG = register("mantis_shrimp_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.MANTIS_SHRIMP.get(), properties));
	public static final DeferredItem<Item> NAKED_MOLE_RAT_SPAWN_EGG = register("naked_mole_rat_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.NAKED_MOLE_RAT.get(), properties));
	public static final DeferredItem<Item> POTOO_SPAWN_EGG = register("potoo_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.POTOO.get(), properties));
	public static final DeferredItem<Item> TENREC_SPAWN_EGG = register("tenrec_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.TENREC.get(), properties));
	public static final DeferredItem<Item> STAR_NOSED_MOLE_SPAWN_EGG = register("star_nosed_mole_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.STAR_NOSED_MOLE.get(), properties));
	public static final DeferredItem<Item> CAECILIAN_SPAWN_EGG = register("caecilian_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CAECILIAN.get(), properties));
	public static final DeferredItem<Item> SEA_PIG_SPAWN_EGG = register("sea_pig_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SEA_PIG.get(), properties));
	public static final DeferredItem<Item> VONTSIRA_SPAWN_EGG = register("vontsira_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.VONTSIRA.get(), properties));
	public static final DeferredItem<Item> COBRA_SPAWN_EGG = register("cobra_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.COBRA.get(), properties));
	public static final DeferredItem<Item> MONGOOSE_SPAWN_EGG = register("mongoose_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.MONGOOSE.get(), properties));
	public static final DeferredItem<Item> RATTLESNAKE_SPAWN_EGG = register("rattlesnake_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.RATTLESNAKE.get(), properties));
	public static final DeferredItem<Item> NARWHAL_SPAWN_EGG = register("narwhal_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.NARWHAL.get(), properties));
	public static final DeferredItem<Item> SEA_LION_SPAWN_EGG = register("sea_lion_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SEA_LION.get(), properties));
	public static final DeferredItem<Item> COYOTE_SPAWN_EGG = register("coyote_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.COYOTE.get(), properties));
	public static final DeferredItem<Item> PYTHON_SPAWN_EGG = register("python_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.PYTHON.get(), properties));
	public static final DeferredItem<Item> WISENT_SPAWN_EGG = register("wisent_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.WISENT.get(), properties));
	public static final DeferredItem<Item> ROADRUNNER_SPAWN_EGG = register("roadrunner_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.ROADRUNNER.get(), properties));
	public static final DeferredItem<Item> GENET_SPAWN_EGG = register("genet_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.GENET.get(), properties));
	public static final DeferredItem<Item> CAPERCAILLIE_SPAWN_EGG = register("capercaillie_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CAPERCAILLIE.get(), properties));
	public static final DeferredItem<Item> GROUSE_SPAWN_EGG = register("grouse_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.GROUSE.get(), properties));
	public static final DeferredItem<Item> TAPIR_SPAWN_EGG = register("tapir_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.TAPIR.get(), properties));
	public static final DeferredItem<Item> TURKEY_SPAWN_EGG = register("turkey_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.TURKEY.get(), properties));
	public static final DeferredItem<Item> RAW_TURKEY = register("raw_turkey", RawTurkeyItem::new);
	public static final DeferredItem<Item> COOKED_TURKEY = register("cooked_turkey", CookedTurkeyItem::new);
	public static final DeferredItem<Item> LAMMERGEIER_SPAWN_EGG = register("lammergeier_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.LAMMERGEIER.get(), properties));
	public static final DeferredItem<Item> HOOPOE_SPAWN_EGG = register("hoopoe_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.HOOPOE.get(), properties));
	public static final DeferredItem<Item> DODO_SPAWN_EGG = register("dodo_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.DODO.get(), properties));
	public static final DeferredItem<Item> WOOLLY_RHINOCEROS_SPAWN_EGG = register("woolly_rhinoceros_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.WOOLLY_RHINOCEROS.get(), properties));
	public static final DeferredItem<Item> SMILODON_SPAWN_EGG = register("smilodon_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SMILODON.get(), properties));
	public static final DeferredItem<Item> PROCOPTODON_SPAWN_EGG = register("procoptodon_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.PROCOPTODON.get(), properties));
	public static final DeferredItem<Item> MARSUPIAL_LION_SPAWN_EGG = register("marsupial_lion_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.MARSUPIAL_LION.get(), properties));
	public static final DeferredItem<Item> THYLACINE_SPAWN_EGG = register("thylacine_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.THYLACINE.get(), properties));
	public static final DeferredItem<Item> WILD_BOAR_SPAWN_EGG = register("wild_boar_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.WILD_BOAR.get(), properties));
	public static final DeferredItem<Item> WOLVERINE_SPAWN_EGG = register("wolverine_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.WOLVERINE.get(), properties));
	public static final DeferredItem<Item> STOAT_SPAWN_EGG = register("stoat_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.STOAT.get(), properties));
	public static final DeferredItem<Item> WEASEL_SPAWN_EGG = register("weasel_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.WEASEL.get(), properties));
	public static final DeferredItem<Item> CORSAC_FOX_SPAWN_EGG = register("corsac_fox_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CORSAC_FOX.get(), properties));
	public static final DeferredItem<Item> SKUNK_SPAWN_EGG = register("skunk_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SKUNK.get(), properties));
	public static final DeferredItem<Item> MANED_WOLF_SPAWN_EGG = register("maned_wolf_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.MANED_WOLF.get(), properties));
	public static final DeferredItem<Item> MUSK_DEER_SPAWN_EGG = register("musk_deer_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.MUSK_DEER.get(), properties));
	public static final DeferredItem<Item> QUAIL_SPAWN_EGG = register("quail_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.QUAIL.get(), properties));
	public static final DeferredItem<Item> RAW_QUAIL = register("raw_quail", RawQuailItem::new);
	public static final DeferredItem<Item> COOKED_QUAIL = register("cooked_quail", CookedQuailItem::new);
	public static final DeferredItem<Item> WHALE_SHARK_SPAWN_EGG = register("whale_shark_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.WHALE_SHARK.get(), properties));
	public static final DeferredItem<Item> MAPLE_WOOD = block(PseudorygiumModBlocks.MAPLE_WOOD);
	public static final DeferredItem<Item> MAPLE_LOG = block(PseudorygiumModBlocks.MAPLE_LOG);
	public static final DeferredItem<Item> MAPLE_PLANKS = block(PseudorygiumModBlocks.MAPLE_PLANKS);
	public static final DeferredItem<Item> MAPLE_LEAVES = block(PseudorygiumModBlocks.MAPLE_LEAVES);
	public static final DeferredItem<Item> MAPLE_STAIRS = block(PseudorygiumModBlocks.MAPLE_STAIRS);
	public static final DeferredItem<Item> MAPLE_SLAB = block(PseudorygiumModBlocks.MAPLE_SLAB);
	public static final DeferredItem<Item> MAPLE_FENCE = block(PseudorygiumModBlocks.MAPLE_FENCE);
	public static final DeferredItem<Item> MAPLE_FENCE_GATE = block(PseudorygiumModBlocks.MAPLE_FENCE_GATE);
	public static final DeferredItem<Item> MAPLE_PRESSURE_PLATE = block(PseudorygiumModBlocks.MAPLE_PRESSURE_PLATE);
	public static final DeferredItem<Item> MAPLE_BUTTON = block(PseudorygiumModBlocks.MAPLE_BUTTON);
	public static final DeferredItem<Item> STRIPPED_MAPLE_LOG = block(PseudorygiumModBlocks.STRIPPED_MAPLE_LOG);
	public static final DeferredItem<Item> STRIPPED_MAPLE_WOOD = block(PseudorygiumModBlocks.STRIPPED_MAPLE_WOOD);
	public static final DeferredItem<Item> MAPLE_DOOR = doubleBlock(PseudorygiumModBlocks.MAPLE_DOOR);
	public static final DeferredItem<Item> MAPLE_TRAPDOOR = block(PseudorygiumModBlocks.MAPLE_TRAPDOOR);
	public static final DeferredItem<Item> MAPLE_SAPLING = block(PseudorygiumModBlocks.MAPLE_SAPLING);
	public static final DeferredItem<Item> SAPPY_MAPLE_LOG = block(PseudorygiumModBlocks.SAPPY_MAPLE_LOG);
	public static final DeferredItem<Item> SAPPY_MAPLE_WOOD = block(PseudorygiumModBlocks.SAPPY_MAPLE_WOOD);
	public static final DeferredItem<Item> SAP_BOTTLE = register("sap_bottle", SapBottleItem::new);
	public static final DeferredItem<Item> MAPLE_SYRUP_BOTTLE = register("maple_syrup_bottle", MapleSyrupBottleItem::new);
	public static final DeferredItem<Item> TERRAPIN_SPAWN_EGG = register("terrapin_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.TERRAPIN.get(), properties));
	public static final DeferredItem<Item> ANOLE_SPAWN_EGG = register("anole_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.ANOLE.get(), properties));
	public static final DeferredItem<Item> AGAMA_SPAWN_EGG = register("agama_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.AGAMA.get(), properties));
	public static final DeferredItem<Item> MOLOCH_SPAWN_EGG = register("moloch_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.MOLOCH.get(), properties));
	public static final DeferredItem<Item> LEAF_TAILED_GECKO_SPAWN_EGG = register("leaf_tailed_gecko_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.LEAF_TAILED_GECKO.get(), properties));
	public static final DeferredItem<Item> CHAMELEON_SPAWN_EGG = register("chameleon_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CHAMELEON.get(), properties));
	public static final DeferredItem<Item> BEECH_WOOD = block(PseudorygiumModBlocks.BEECH_WOOD);
	public static final DeferredItem<Item> BEECH_LOG = block(PseudorygiumModBlocks.BEECH_LOG);
	public static final DeferredItem<Item> BEECH_PLANKS = block(PseudorygiumModBlocks.BEECH_PLANKS);
	public static final DeferredItem<Item> BEECH_LEAVES = block(PseudorygiumModBlocks.BEECH_LEAVES);
	public static final DeferredItem<Item> BEECH_STAIRS = block(PseudorygiumModBlocks.BEECH_STAIRS);
	public static final DeferredItem<Item> BEECH_SLAB = block(PseudorygiumModBlocks.BEECH_SLAB);
	public static final DeferredItem<Item> BEECH_FENCE = block(PseudorygiumModBlocks.BEECH_FENCE);
	public static final DeferredItem<Item> BEECH_FENCE_GATE = block(PseudorygiumModBlocks.BEECH_FENCE_GATE);
	public static final DeferredItem<Item> BEECH_PRESSURE_PLATE = block(PseudorygiumModBlocks.BEECH_PRESSURE_PLATE);
	public static final DeferredItem<Item> BEECH_BUTTON = block(PseudorygiumModBlocks.BEECH_BUTTON);
	public static final DeferredItem<Item> STRIPPED_BEECH_WOOD = block(PseudorygiumModBlocks.STRIPPED_BEECH_WOOD);
	public static final DeferredItem<Item> STRIPPED_BEECH_LOG = block(PseudorygiumModBlocks.STRIPPED_BEECH_LOG);
	public static final DeferredItem<Item> BEECH_DOOR = doubleBlock(PseudorygiumModBlocks.BEECH_DOOR);
	public static final DeferredItem<Item> BEECH_TRAPDOOR = block(PseudorygiumModBlocks.BEECH_TRAPDOOR);
	public static final DeferredItem<Item> PALM_WOOD = block(PseudorygiumModBlocks.PALM_WOOD);
	public static final DeferredItem<Item> PALM_LOG = block(PseudorygiumModBlocks.PALM_LOG);
	public static final DeferredItem<Item> PALM_PLANKS = block(PseudorygiumModBlocks.PALM_PLANKS);
	public static final DeferredItem<Item> PALM_LEAVES = block(PseudorygiumModBlocks.PALM_LEAVES);
	public static final DeferredItem<Item> PALM_STAIRS = block(PseudorygiumModBlocks.PALM_STAIRS);
	public static final DeferredItem<Item> PALM_SLAB = block(PseudorygiumModBlocks.PALM_SLAB);
	public static final DeferredItem<Item> PALM_FENCE = block(PseudorygiumModBlocks.PALM_FENCE);
	public static final DeferredItem<Item> PALM_FENCE_GATE = block(PseudorygiumModBlocks.PALM_FENCE_GATE);
	public static final DeferredItem<Item> PALM_PRESSURE_PLATE = block(PseudorygiumModBlocks.PALM_PRESSURE_PLATE);
	public static final DeferredItem<Item> PALM_BUTTON = block(PseudorygiumModBlocks.PALM_BUTTON);
	public static final DeferredItem<Item> STRIPPED_PALM_WOOD = block(PseudorygiumModBlocks.STRIPPED_PALM_WOOD);
	public static final DeferredItem<Item> STRIPPED_PALM_LOG = block(PseudorygiumModBlocks.STRIPPED_PALM_LOG);
	public static final DeferredItem<Item> PALM_DOOR = doubleBlock(PseudorygiumModBlocks.PALM_DOOR);
	public static final DeferredItem<Item> PALM_TRAPDOOR = block(PseudorygiumModBlocks.PALM_TRAPDOOR);
	public static final DeferredItem<Item> PALM_SAPLING = block(PseudorygiumModBlocks.PALM_SAPLING);
	public static final DeferredItem<Item> BEECH_SAPLING = block(PseudorygiumModBlocks.BEECH_SAPLING);
	public static final DeferredItem<Item> ASPEN_WOOD = block(PseudorygiumModBlocks.ASPEN_WOOD);
	public static final DeferredItem<Item> ASPEN_LOG = block(PseudorygiumModBlocks.ASPEN_LOG);
	public static final DeferredItem<Item> ASPEN_PLANKS = block(PseudorygiumModBlocks.ASPEN_PLANKS);
	public static final DeferredItem<Item> ASPEN_LEAVES = block(PseudorygiumModBlocks.ASPEN_LEAVES);
	public static final DeferredItem<Item> ASPEN_STAIRS = block(PseudorygiumModBlocks.ASPEN_STAIRS);
	public static final DeferredItem<Item> ASPEN_SLAB = block(PseudorygiumModBlocks.ASPEN_SLAB);
	public static final DeferredItem<Item> ASPEN_FENCE = block(PseudorygiumModBlocks.ASPEN_FENCE);
	public static final DeferredItem<Item> ASPEN_FENCE_GATE = block(PseudorygiumModBlocks.ASPEN_FENCE_GATE);
	public static final DeferredItem<Item> ASPEN_PRESSURE_PLATE = block(PseudorygiumModBlocks.ASPEN_PRESSURE_PLATE);
	public static final DeferredItem<Item> ASPEN_BUTTON = block(PseudorygiumModBlocks.ASPEN_BUTTON);
	public static final DeferredItem<Item> ASPEN_SAPLING = block(PseudorygiumModBlocks.ASPEN_SAPLING);
	public static final DeferredItem<Item> STRIPPED_ASPEN_WOOD = block(PseudorygiumModBlocks.STRIPPED_ASPEN_WOOD);
	public static final DeferredItem<Item> STRIPPED_ASPEN_LOG = block(PseudorygiumModBlocks.STRIPPED_ASPEN_LOG);
	public static final DeferredItem<Item> ASPEN_DOOR = doubleBlock(PseudorygiumModBlocks.ASPEN_DOOR);
	public static final DeferredItem<Item> ASPEN_TRAPDOOR = block(PseudorygiumModBlocks.ASPEN_TRAPDOOR);
	public static final DeferredItem<Item> GINKGO_WOOD = block(PseudorygiumModBlocks.GINKGO_WOOD);
	public static final DeferredItem<Item> GINKGO_LOG = block(PseudorygiumModBlocks.GINKGO_LOG);
	public static final DeferredItem<Item> GINKGO_PLANKS = block(PseudorygiumModBlocks.GINKGO_PLANKS);
	public static final DeferredItem<Item> GINKGO_LEAVES = block(PseudorygiumModBlocks.GINKGO_LEAVES);
	public static final DeferredItem<Item> GINKGO_STAIRS = block(PseudorygiumModBlocks.GINKGO_STAIRS);
	public static final DeferredItem<Item> GINKGO_SLAB = block(PseudorygiumModBlocks.GINKGO_SLAB);
	public static final DeferredItem<Item> GINKGO_FENCE = block(PseudorygiumModBlocks.GINKGO_FENCE);
	public static final DeferredItem<Item> GINKGO_FENCE_GATE = block(PseudorygiumModBlocks.GINKGO_FENCE_GATE);
	public static final DeferredItem<Item> GINKGO_PRESSURE_PLATE = block(PseudorygiumModBlocks.GINKGO_PRESSURE_PLATE);
	public static final DeferredItem<Item> GINKGO_BUTTON = block(PseudorygiumModBlocks.GINKGO_BUTTON);
	public static final DeferredItem<Item> STRIPPED_GINKGO_WOOD = block(PseudorygiumModBlocks.STRIPPED_GINKGO_WOOD);
	public static final DeferredItem<Item> STRIPPED_GINKGO_LOG = block(PseudorygiumModBlocks.STRIPPED_GINKGO_LOG);
	public static final DeferredItem<Item> GINKGO_DOOR = doubleBlock(PseudorygiumModBlocks.GINKGO_DOOR);
	public static final DeferredItem<Item> GINKGO_TRAPDOOR = block(PseudorygiumModBlocks.GINKGO_TRAPDOOR);
	public static final DeferredItem<Item> GINKGO_SAPLING = block(PseudorygiumModBlocks.GINKGO_SAPLING);
	public static final DeferredItem<Item> EUCALYPTUS_WOOD = block(PseudorygiumModBlocks.EUCALYPTUS_WOOD);
	public static final DeferredItem<Item> EUCALYPTUS_LOG = block(PseudorygiumModBlocks.EUCALYPTUS_LOG);
	public static final DeferredItem<Item> EUCALYPTUS_PLANKS = block(PseudorygiumModBlocks.EUCALYPTUS_PLANKS);
	public static final DeferredItem<Item> EUCALYPTUS_LEAVES = block(PseudorygiumModBlocks.EUCALYPTUS_LEAVES);
	public static final DeferredItem<Item> EUCALYPTUS_STAIRS = block(PseudorygiumModBlocks.EUCALYPTUS_STAIRS);
	public static final DeferredItem<Item> EUCALYPTUS_SLAB = block(PseudorygiumModBlocks.EUCALYPTUS_SLAB);
	public static final DeferredItem<Item> EUCALYPTUS_FENCE = block(PseudorygiumModBlocks.EUCALYPTUS_FENCE);
	public static final DeferredItem<Item> EUCALYPTUS_FENCE_GATE = block(PseudorygiumModBlocks.EUCALYPTUS_FENCE_GATE);
	public static final DeferredItem<Item> EUCALYPTUS_PRESSURE_PLATE = block(PseudorygiumModBlocks.EUCALYPTUS_PRESSURE_PLATE);
	public static final DeferredItem<Item> EUCALYPTUS_BUTTON = block(PseudorygiumModBlocks.EUCALYPTUS_BUTTON);
	public static final DeferredItem<Item> STRIPPED_EUCALYPTUS_WOOD = block(PseudorygiumModBlocks.STRIPPED_EUCALYPTUS_WOOD);
	public static final DeferredItem<Item> STRIPPED_EUCALYPTUS_LOG = block(PseudorygiumModBlocks.STRIPPED_EUCALYPTUS_LOG);
	public static final DeferredItem<Item> EUCALYPTUS_DOOR = doubleBlock(PseudorygiumModBlocks.EUCALYPTUS_DOOR);
	public static final DeferredItem<Item> EUCALYPTUS_TRAPDOOR = block(PseudorygiumModBlocks.EUCALYPTUS_TRAPDOOR);
	public static final DeferredItem<Item> EUCALYPTUS_SAPLING = block(PseudorygiumModBlocks.EUCALYPTUS_SAPLING);
	public static final DeferredItem<Item> STRAWBERRY = register("strawberry", StrawberryItem::new);
	public static final DeferredItem<Item> SILVER_INGOT = register("silver_ingot", SilverIngotItem::new);
	public static final DeferredItem<Item> SILVER_ORE = block(PseudorygiumModBlocks.SILVER_ORE);
	public static final DeferredItem<Item> SILVER_BLOCK = block(PseudorygiumModBlocks.SILVER_BLOCK);
	public static final DeferredItem<Item> RAW_SILVER = register("raw_silver", RawSilverItem::new);
	public static final DeferredItem<Item> KATANA = register("katana", KatanaItem::new);
	public static final DeferredItem<Item> NETHERITE_KATANA = register("netherite_katana", NetheriteKatanaItem::new);
	public static final DeferredItem<Item> DEEPSLATE_SILVER_ORE = block(PseudorygiumModBlocks.DEEPSLATE_SILVER_ORE);
	public static final DeferredItem<Item> RAW_SILVER_BLOCK = block(PseudorygiumModBlocks.RAW_SILVER_BLOCK);
	public static final DeferredItem<Item> CARP_SPAWN_EGG = register("carp_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CARP.get(), properties));
	public static final DeferredItem<Item> CARP_BUCKET = register("carp_bucket", CarpBucketItem::new);
	public static final DeferredItem<Item> OPEN_COCONUT = register("open_coconut", OpenCoconutItem::new);
	public static final DeferredItem<Item> COCONUT_BLOCK = block(PseudorygiumModBlocks.COCONUT_BLOCK);
	public static final DeferredItem<Item> RAW_CARP = register("raw_carp", RawCarpItem::new);
	public static final DeferredItem<Item> COOKED_CARP = register("cooked_carp", CookedCarpItem::new);
	public static final DeferredItem<Item> COBALT_INGOT = register("cobalt_ingot", CobaltIngotItem::new);
	public static final DeferredItem<Item> COBALT_ORE = block(PseudorygiumModBlocks.COBALT_ORE);
	public static final DeferredItem<Item> COBALT_BLOCK = block(PseudorygiumModBlocks.COBALT_BLOCK);
	public static final DeferredItem<Item> COBALT_PICKAXE = register("cobalt_pickaxe", CobaltPickaxeItem::new);
	public static final DeferredItem<Item> COBALT_AXE = register("cobalt_axe", CobaltAxeItem::new);
	public static final DeferredItem<Item> COBALT_SWORD = register("cobalt_sword", CobaltSwordItem::new);
	public static final DeferredItem<Item> COBALT_SHOVEL = register("cobalt_shovel", CobaltShovelItem::new);
	public static final DeferredItem<Item> COBALT_HOE = register("cobalt_hoe", CobaltHoeItem::new);
	public static final DeferredItem<Item> COBALT_ARMOR_HELMET = register("cobalt_armor_helmet", CobaltArmorItem.Helmet::new);
	public static final DeferredItem<Item> COBALT_ARMOR_CHESTPLATE = register("cobalt_armor_chestplate", CobaltArmorItem.Chestplate::new);
	public static final DeferredItem<Item> COBALT_ARMOR_LEGGINGS = register("cobalt_armor_leggings", CobaltArmorItem.Leggings::new);
	public static final DeferredItem<Item> COBALT_ARMOR_BOOTS = register("cobalt_armor_boots", CobaltArmorItem.Boots::new);
	public static final DeferredItem<Item> SILVER_NUGGET = register("silver_nugget", SilverNuggetItem::new);
	public static final DeferredItem<Item> DEEPSLATE_COBALT_ORE = block(PseudorygiumModBlocks.DEEPSLATE_COBALT_ORE);
	public static final DeferredItem<Item> LEOPARD_SPAWN_EGG = register("leopard_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.LEOPARD.get(), properties));
	public static final DeferredItem<Item> SAOLA_SPAWN_EGG = register("saola_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SAOLA.get(), properties));
	public static final DeferredItem<Item> PRONGHORN_SPAWN_EGG = register("pronghorn_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.PRONGHORN.get(), properties));
	public static final DeferredItem<Item> REGULAR_BUSH = block(PseudorygiumModBlocks.REGULAR_BUSH);
	public static final DeferredItem<Item> DOG_SPAWN_EGG = register("dog_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.DOG.get(), properties));
	public static final DeferredItem<Item> SWALLOW_SPAWN_EGG = register("swallow_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SWALLOW.get(), properties));
	public static final DeferredItem<Item> BEAVER_SPAWN_EGG = register("beaver_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.BEAVER.get(), properties));
	public static final DeferredItem<Item> GRASS_SNAKE_SPAWN_EGG = register("grass_snake_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.GRASS_SNAKE.get(), properties));
	public static final DeferredItem<Item> CORAL_SNAKE_SPAWN_EGG = register("coral_snake_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CORAL_SNAKE.get(), properties));
	public static final DeferredItem<Item> LAVENDER = block(PseudorygiumModBlocks.LAVENDER);
	public static final DeferredItem<Item> DAFFODIL = block(PseudorygiumModBlocks.DAFFODIL);
	public static final DeferredItem<Item> SISKIN_SPAWN_EGG = register("siskin_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.SISKIN.get(), properties));
	public static final DeferredItem<Item> CARDINAL_SPAWN_EGG = register("cardinal_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CARDINAL.get(), properties));
	public static final DeferredItem<Item> CANARY_SPAWN_EGG = register("canary_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.CANARY.get(), properties));
	public static final DeferredItem<Item> KOALA_SPAWN_EGG = register("koala_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.KOALA.get(), properties));
	public static final DeferredItem<Item> QUICKSAND_BUCKET = register("quicksand_bucket", QuicksandBucketItem::new);
	public static final DeferredItem<Item> QUICKSAND = block(PseudorygiumModBlocks.QUICKSAND);
	public static final DeferredItem<Item> HARE_SPAWN_EGG = register("hare_spawn_egg", properties -> new SpawnEggItem(PseudorygiumModEntities.HARE.get(), properties));
	public static final DeferredItem<Item> TOMATO = register("tomato", TomatoItem::new);
	public static final DeferredItem<Item> TOMATO_SEEDS = register("tomato_seeds", TomatoSeedsItem::new);
	public static final DeferredItem<Item> MAIZE = register("maize", MaizeItem::new);
	public static final DeferredItem<Item> MAIZE_SEEDS = register("maize_seeds", MaizeSeedsItem::new);
	public static final DeferredItem<Item> MORIN_KHUUR = register("morin_khuur", MorinKhuurItem::new);
	public static final DeferredItem<Item> BOOMERANG = register("boomerang", BoomerangItem::new);
	public static final DeferredItem<Item> TOMATO_CROP = block(PseudorygiumModBlocks.TOMATO_CROP);

	// Start of user code block custom items
	// End of user code block custom items
	private static <I extends Item> DeferredItem<I> register(String name, Function<Item.Properties, ? extends I> supplier) {
		return REGISTRY.registerItem(name, supplier, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return REGISTRY.registerItem(block.getId().getPath(), properties -> new BlockItem(block.get(), properties), new Item.Properties());
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return REGISTRY.registerItem(block.getId().getPath(), properties -> new DoubleHighBlockItem(block.get(), properties), new Item.Properties());
	}
}
