
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package com.pseudorygium.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.client.event.RegisterColorHandlersEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

import com.pseudorygium.block.WillowWoodBlock;
import com.pseudorygium.block.WillowTrapdoorBlock;
import com.pseudorygium.block.WillowStairsBlock;
import com.pseudorygium.block.WillowSlabBlock;
import com.pseudorygium.block.WillowSaplingBlock;
import com.pseudorygium.block.WillowPressurePlateBlock;
import com.pseudorygium.block.WillowPlanksBlock;
import com.pseudorygium.block.WillowLogBlock;
import com.pseudorygium.block.WillowLeavesBlock;
import com.pseudorygium.block.WillowFenceGateBlock;
import com.pseudorygium.block.WillowFenceBlock;
import com.pseudorygium.block.WillowDoorBlock;
import com.pseudorygium.block.WillowButtonBlock;
import com.pseudorygium.block.VenusFlytrapBlock;
import com.pseudorygium.block.StrippedWillowWoodBlock;
import com.pseudorygium.block.StrippedWillowLogBlock;
import com.pseudorygium.block.StrippedPoplarWoodBlock;
import com.pseudorygium.block.StrippedPoplarLogBlock;
import com.pseudorygium.block.StrippedPalmWoodBlock;
import com.pseudorygium.block.StrippedPalmLogBlock;
import com.pseudorygium.block.StrippedMapleWoodBlock;
import com.pseudorygium.block.StrippedMapleLogBlock;
import com.pseudorygium.block.StrippedLindenWoodBlock;
import com.pseudorygium.block.StrippedLindenLogBlock;
import com.pseudorygium.block.StrippedHornbeamWoodBlock;
import com.pseudorygium.block.StrippedHormbeamLogBlock;
import com.pseudorygium.block.StrippedGinkgoWoodBlock;
import com.pseudorygium.block.StrippedGinkgoLogBlock;
import com.pseudorygium.block.StrippedEucalyptusWoodBlock;
import com.pseudorygium.block.StrippedEucalyptusLogBlock;
import com.pseudorygium.block.StrippedBeechWoodBlock;
import com.pseudorygium.block.StrippedBeechLogBlock;
import com.pseudorygium.block.StrippedBaobabWoodBlock;
import com.pseudorygium.block.StrippedBaobabLogBlock;
import com.pseudorygium.block.StrippedAspenWoodBlock;
import com.pseudorygium.block.StrippedAspenLogBlock;
import com.pseudorygium.block.SilverOreBlock;
import com.pseudorygium.block.SilverBlockBlock;
import com.pseudorygium.block.SappyMapleWoodBlock;
import com.pseudorygium.block.SappyMapleLogBlock;
import com.pseudorygium.block.RegularBushBlock;
import com.pseudorygium.block.RawSilverBlockBlock;
import com.pseudorygium.block.QuicksandBlock;
import com.pseudorygium.block.PoplarWoodBlock;
import com.pseudorygium.block.PoplarTrapdoorBlock;
import com.pseudorygium.block.PoplarStairsBlock;
import com.pseudorygium.block.PoplarSlabBlock;
import com.pseudorygium.block.PoplarSaplingBlock;
import com.pseudorygium.block.PoplarPressurePlateBlock;
import com.pseudorygium.block.PoplarPlanksBlock;
import com.pseudorygium.block.PoplarLogBlock;
import com.pseudorygium.block.PoplarLeavesBlock;
import com.pseudorygium.block.PoplarFenceGateBlock;
import com.pseudorygium.block.PoplarFenceBlock;
import com.pseudorygium.block.PoplarDoorBlock;
import com.pseudorygium.block.PoplarButtonBlock;
import com.pseudorygium.block.PermafrostBlock;
import com.pseudorygium.block.PeatBlockBlock;
import com.pseudorygium.block.PalmWoodBlock;
import com.pseudorygium.block.PalmTrapdoorBlock;
import com.pseudorygium.block.PalmStairsBlock;
import com.pseudorygium.block.PalmSlabBlock;
import com.pseudorygium.block.PalmSaplingBlock;
import com.pseudorygium.block.PalmPressurePlateBlock;
import com.pseudorygium.block.PalmPlanksBlock;
import com.pseudorygium.block.PalmLogBlock;
import com.pseudorygium.block.PalmLeavesBlock;
import com.pseudorygium.block.PalmFenceGateBlock;
import com.pseudorygium.block.PalmFenceBlock;
import com.pseudorygium.block.PalmDoorBlock;
import com.pseudorygium.block.PalmButtonBlock;
import com.pseudorygium.block.OutbackBushBlock;
import com.pseudorygium.block.MapleWoodBlock;
import com.pseudorygium.block.MapleTrapdoorBlock;
import com.pseudorygium.block.MapleStairsBlock;
import com.pseudorygium.block.MapleSlabBlock;
import com.pseudorygium.block.MapleSaplingBlock;
import com.pseudorygium.block.MaplePressurePlateBlock;
import com.pseudorygium.block.MaplePlanksBlock;
import com.pseudorygium.block.MapleLogBlock;
import com.pseudorygium.block.MapleLeavesBlock;
import com.pseudorygium.block.MapleFenceGateBlock;
import com.pseudorygium.block.MapleFenceBlock;
import com.pseudorygium.block.MapleDoorBlock;
import com.pseudorygium.block.MapleButtonBlock;
import com.pseudorygium.block.LindenWoodBlock;
import com.pseudorygium.block.LindenTrapdoorBlock;
import com.pseudorygium.block.LindenStairsBlock;
import com.pseudorygium.block.LindenSlabBlock;
import com.pseudorygium.block.LindenSaplingBlock;
import com.pseudorygium.block.LindenPressurePlateBlock;
import com.pseudorygium.block.LindenPlanksBlock;
import com.pseudorygium.block.LindenLogBlock;
import com.pseudorygium.block.LindenLeavesBlock;
import com.pseudorygium.block.LindenFenceGateBlock;
import com.pseudorygium.block.LindenFenceBlock;
import com.pseudorygium.block.LindenDoorBlock;
import com.pseudorygium.block.LindenButtonBlock;
import com.pseudorygium.block.LavenderBlock;
import com.pseudorygium.block.HornbeamWoodBlock;
import com.pseudorygium.block.HornbeamTrapdoorBlock;
import com.pseudorygium.block.HornbeamStairsBlock;
import com.pseudorygium.block.HornbeamSlabBlock;
import com.pseudorygium.block.HornbeamSaplingBlock;
import com.pseudorygium.block.HornbeamPressurePlateBlock;
import com.pseudorygium.block.HornbeamPlanksBlock;
import com.pseudorygium.block.HornbeamLogBlock;
import com.pseudorygium.block.HornbeamLeavesBlock;
import com.pseudorygium.block.HornbeamFenceGateBlock;
import com.pseudorygium.block.HornbeamFenceBlock;
import com.pseudorygium.block.HornbeamDoorBlock;
import com.pseudorygium.block.HornbeamButtonBlock;
import com.pseudorygium.block.GinkgoWoodBlock;
import com.pseudorygium.block.GinkgoTrapdoorBlock;
import com.pseudorygium.block.GinkgoStairsBlock;
import com.pseudorygium.block.GinkgoSlabBlock;
import com.pseudorygium.block.GinkgoSaplingBlock;
import com.pseudorygium.block.GinkgoPressurePlateBlock;
import com.pseudorygium.block.GinkgoPlanksBlock;
import com.pseudorygium.block.GinkgoLogBlock;
import com.pseudorygium.block.GinkgoLeavesBlock;
import com.pseudorygium.block.GinkgoFenceGateBlock;
import com.pseudorygium.block.GinkgoFenceBlock;
import com.pseudorygium.block.GinkgoDoorBlock;
import com.pseudorygium.block.GinkgoButtonBlock;
import com.pseudorygium.block.FormicariumBlock;
import com.pseudorygium.block.EucalyptusWoodBlock;
import com.pseudorygium.block.EucalyptusTrapdoorBlock;
import com.pseudorygium.block.EucalyptusStairsBlock;
import com.pseudorygium.block.EucalyptusSlabBlock;
import com.pseudorygium.block.EucalyptusSaplingBlock;
import com.pseudorygium.block.EucalyptusPressurePlateBlock;
import com.pseudorygium.block.EucalyptusPlanksBlock;
import com.pseudorygium.block.EucalyptusLogBlock;
import com.pseudorygium.block.EucalyptusLeavesBlock;
import com.pseudorygium.block.EucalyptusFenceGateBlock;
import com.pseudorygium.block.EucalyptusFenceBlock;
import com.pseudorygium.block.EucalyptusDoorBlock;
import com.pseudorygium.block.EucalyptusButtonBlock;
import com.pseudorygium.block.DeepslateSilverOreBlock;
import com.pseudorygium.block.DeepslateCobaltOreBlock;
import com.pseudorygium.block.DaffodilBlock;
import com.pseudorygium.block.ColdDesertGrassBlock;
import com.pseudorygium.block.ColdDesertDirtBlock;
import com.pseudorygium.block.CoconutBlockBlock;
import com.pseudorygium.block.CobaltOreBlock;
import com.pseudorygium.block.CobaltBlockBlock;
import com.pseudorygium.block.CamelthornBlock;
import com.pseudorygium.block.BeechWoodBlock;
import com.pseudorygium.block.BeechTrapdoorBlock;
import com.pseudorygium.block.BeechStairsBlock;
import com.pseudorygium.block.BeechSlabBlock;
import com.pseudorygium.block.BeechSaplingBlock;
import com.pseudorygium.block.BeechPressurePlateBlock;
import com.pseudorygium.block.BeechPlanksBlock;
import com.pseudorygium.block.BeechLogBlock;
import com.pseudorygium.block.BeechLeavesBlock;
import com.pseudorygium.block.BeechFenceGateBlock;
import com.pseudorygium.block.BeechFenceBlock;
import com.pseudorygium.block.BeechDoorBlock;
import com.pseudorygium.block.BeechButtonBlock;
import com.pseudorygium.block.BaobabWoodBlock;
import com.pseudorygium.block.BaobabTrapdoorBlock;
import com.pseudorygium.block.BaobabStairsBlock;
import com.pseudorygium.block.BaobabSlabBlock;
import com.pseudorygium.block.BaobabSaplingBlock;
import com.pseudorygium.block.BaobabPressurePlateBlock;
import com.pseudorygium.block.BaobabPlanksBlock;
import com.pseudorygium.block.BaobabLogBlock;
import com.pseudorygium.block.BaobabLeavesBlock;
import com.pseudorygium.block.BaobabFenceGateBlock;
import com.pseudorygium.block.BaobabFenceBlock;
import com.pseudorygium.block.BaobabDoorBlock;
import com.pseudorygium.block.BaobabButtonBlock;
import com.pseudorygium.block.AspenWoodBlock;
import com.pseudorygium.block.AspenTrapdoorBlock;
import com.pseudorygium.block.AspenStairsBlock;
import com.pseudorygium.block.AspenSlabBlock;
import com.pseudorygium.block.AspenSaplingBlock;
import com.pseudorygium.block.AspenPressurePlateBlock;
import com.pseudorygium.block.AspenPlanksBlock;
import com.pseudorygium.block.AspenLogBlock;
import com.pseudorygium.block.AspenLeavesBlock;
import com.pseudorygium.block.AspenFenceGateBlock;
import com.pseudorygium.block.AspenFenceBlock;
import com.pseudorygium.block.AspenDoorBlock;
import com.pseudorygium.block.AspenButtonBlock;
import com.pseudorygium.block.AnthillBlock;
import com.pseudorygium.PseudorygiumMod;

public class PseudorygiumModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(PseudorygiumMod.MODID);
	public static final DeferredBlock<Block> HORNBEAM_WOOD = REGISTRY.register("hornbeam_wood", HornbeamWoodBlock::new);
	public static final DeferredBlock<Block> HORNBEAM_LOG = REGISTRY.register("hornbeam_log", HornbeamLogBlock::new);
	public static final DeferredBlock<Block> HORNBEAM_PLANKS = REGISTRY.register("hornbeam_planks", HornbeamPlanksBlock::new);
	public static final DeferredBlock<Block> HORNBEAM_LEAVES = REGISTRY.register("hornbeam_leaves", HornbeamLeavesBlock::new);
	public static final DeferredBlock<Block> HORNBEAM_STAIRS = REGISTRY.register("hornbeam_stairs", HornbeamStairsBlock::new);
	public static final DeferredBlock<Block> HORNBEAM_SLAB = REGISTRY.register("hornbeam_slab", HornbeamSlabBlock::new);
	public static final DeferredBlock<Block> HORNBEAM_FENCE = REGISTRY.register("hornbeam_fence", HornbeamFenceBlock::new);
	public static final DeferredBlock<Block> HORNBEAM_FENCE_GATE = REGISTRY.register("hornbeam_fence_gate", HornbeamFenceGateBlock::new);
	public static final DeferredBlock<Block> HORNBEAM_PRESSURE_PLATE = REGISTRY.register("hornbeam_pressure_plate", HornbeamPressurePlateBlock::new);
	public static final DeferredBlock<Block> HORNBEAM_BUTTON = REGISTRY.register("hornbeam_button", HornbeamButtonBlock::new);
	public static final DeferredBlock<Block> HORNBEAM_SAPLING = REGISTRY.register("hornbeam_sapling", HornbeamSaplingBlock::new);
	public static final DeferredBlock<Block> LINDEN_WOOD = REGISTRY.register("linden_wood", LindenWoodBlock::new);
	public static final DeferredBlock<Block> LINDEN_LOG = REGISTRY.register("linden_log", LindenLogBlock::new);
	public static final DeferredBlock<Block> LINDEN_PLANKS = REGISTRY.register("linden_planks", LindenPlanksBlock::new);
	public static final DeferredBlock<Block> LINDEN_LEAVES = REGISTRY.register("linden_leaves", LindenLeavesBlock::new);
	public static final DeferredBlock<Block> LINDEN_STAIRS = REGISTRY.register("linden_stairs", LindenStairsBlock::new);
	public static final DeferredBlock<Block> LINDEN_SLAB = REGISTRY.register("linden_slab", LindenSlabBlock::new);
	public static final DeferredBlock<Block> LINDEN_FENCE = REGISTRY.register("linden_fence", LindenFenceBlock::new);
	public static final DeferredBlock<Block> LINDEN_FENCE_GATE = REGISTRY.register("linden_fence_gate", LindenFenceGateBlock::new);
	public static final DeferredBlock<Block> LINDEN_PRESSURE_PLATE = REGISTRY.register("linden_pressure_plate", LindenPressurePlateBlock::new);
	public static final DeferredBlock<Block> LINDEN_BUTTON = REGISTRY.register("linden_button", LindenButtonBlock::new);
	public static final DeferredBlock<Block> HORNBEAM_DOOR = REGISTRY.register("hornbeam_door", HornbeamDoorBlock::new);
	public static final DeferredBlock<Block> PERMAFROST = REGISTRY.register("permafrost", PermafrostBlock::new);
	public static final DeferredBlock<Block> LINDEN_DOOR = REGISTRY.register("linden_door", LindenDoorBlock::new);
	public static final DeferredBlock<Block> HORNBEAM_TRAPDOOR = REGISTRY.register("hornbeam_trapdoor", HornbeamTrapdoorBlock::new);
	public static final DeferredBlock<Block> LINDEN_TRAPDOOR = REGISTRY.register("linden_trapdoor", LindenTrapdoorBlock::new);
	public static final DeferredBlock<Block> LINDEN_SAPLING = REGISTRY.register("linden_sapling", LindenSaplingBlock::new);
	public static final DeferredBlock<Block> PEAT_BLOCK = REGISTRY.register("peat_block", PeatBlockBlock::new);
	public static final DeferredBlock<Block> WILLOW_WOOD = REGISTRY.register("willow_wood", WillowWoodBlock::new);
	public static final DeferredBlock<Block> WILLOW_LOG = REGISTRY.register("willow_log", WillowLogBlock::new);
	public static final DeferredBlock<Block> WILLOW_PLANKS = REGISTRY.register("willow_planks", WillowPlanksBlock::new);
	public static final DeferredBlock<Block> WILLOW_LEAVES = REGISTRY.register("willow_leaves", WillowLeavesBlock::new);
	public static final DeferredBlock<Block> WILLOW_STAIRS = REGISTRY.register("willow_stairs", WillowStairsBlock::new);
	public static final DeferredBlock<Block> WILLOW_SLAB = REGISTRY.register("willow_slab", WillowSlabBlock::new);
	public static final DeferredBlock<Block> WILLOW_FENCE = REGISTRY.register("willow_fence", WillowFenceBlock::new);
	public static final DeferredBlock<Block> WILLOW_FENCE_GATE = REGISTRY.register("willow_fence_gate", WillowFenceGateBlock::new);
	public static final DeferredBlock<Block> WILLOW_PRESSURE_PLATE = REGISTRY.register("willow_pressure_plate", WillowPressurePlateBlock::new);
	public static final DeferredBlock<Block> WILLOW_BUTTON = REGISTRY.register("willow_button", WillowButtonBlock::new);
	public static final DeferredBlock<Block> WILLOW_SAPLING = REGISTRY.register("willow_sapling", WillowSaplingBlock::new);
	public static final DeferredBlock<Block> WILLOW_DOOR = REGISTRY.register("willow_door", WillowDoorBlock::new);
	public static final DeferredBlock<Block> WILLOW_TRAPDOOR = REGISTRY.register("willow_trapdoor", WillowTrapdoorBlock::new);
	public static final DeferredBlock<Block> VENUS_FLYTRAP = REGISTRY.register("venus_flytrap", VenusFlytrapBlock::new);
	public static final DeferredBlock<Block> OUTBACK_BUSH = REGISTRY.register("outback_bush", OutbackBushBlock::new);
	public static final DeferredBlock<Block> STRIPPED_HORMBEAM_LOG = REGISTRY.register("stripped_hormbeam_log", StrippedHormbeamLogBlock::new);
	public static final DeferredBlock<Block> STRIPPED_HORNBEAM_WOOD = REGISTRY.register("stripped_hornbeam_wood", StrippedHornbeamWoodBlock::new);
	public static final DeferredBlock<Block> STRIPPED_WILLOW_LOG = REGISTRY.register("stripped_willow_log", StrippedWillowLogBlock::new);
	public static final DeferredBlock<Block> STRIPPED_WILLOW_WOOD = REGISTRY.register("stripped_willow_wood", StrippedWillowWoodBlock::new);
	public static final DeferredBlock<Block> STRIPPED_LINDEN_WOOD = REGISTRY.register("stripped_linden_wood", StrippedLindenWoodBlock::new);
	public static final DeferredBlock<Block> STRIPPED_LINDEN_LOG = REGISTRY.register("stripped_linden_log", StrippedLindenLogBlock::new);
	public static final DeferredBlock<Block> POPLAR_WOOD = REGISTRY.register("poplar_wood", PoplarWoodBlock::new);
	public static final DeferredBlock<Block> POPLAR_LOG = REGISTRY.register("poplar_log", PoplarLogBlock::new);
	public static final DeferredBlock<Block> POPLAR_PLANKS = REGISTRY.register("poplar_planks", PoplarPlanksBlock::new);
	public static final DeferredBlock<Block> POPLAR_LEAVES = REGISTRY.register("poplar_leaves", PoplarLeavesBlock::new);
	public static final DeferredBlock<Block> POPLAR_STAIRS = REGISTRY.register("poplar_stairs", PoplarStairsBlock::new);
	public static final DeferredBlock<Block> POPLAR_SLAB = REGISTRY.register("poplar_slab", PoplarSlabBlock::new);
	public static final DeferredBlock<Block> POPLAR_FENCE = REGISTRY.register("poplar_fence", PoplarFenceBlock::new);
	public static final DeferredBlock<Block> POPLAR_FENCE_GATE = REGISTRY.register("poplar_fence_gate", PoplarFenceGateBlock::new);
	public static final DeferredBlock<Block> POPLAR_PRESSURE_PLATE = REGISTRY.register("poplar_pressure_plate", PoplarPressurePlateBlock::new);
	public static final DeferredBlock<Block> POPLAR_BUTTON = REGISTRY.register("poplar_button", PoplarButtonBlock::new);
	public static final DeferredBlock<Block> STRIPPED_POPLAR_WOOD = REGISTRY.register("stripped_poplar_wood", StrippedPoplarWoodBlock::new);
	public static final DeferredBlock<Block> STRIPPED_POPLAR_LOG = REGISTRY.register("stripped_poplar_log", StrippedPoplarLogBlock::new);
	public static final DeferredBlock<Block> POPLAR_DOOR = REGISTRY.register("poplar_door", PoplarDoorBlock::new);
	public static final DeferredBlock<Block> POPLAR_TRAPDOOR = REGISTRY.register("poplar_trapdoor", PoplarTrapdoorBlock::new);
	public static final DeferredBlock<Block> POPLAR_SAPLING = REGISTRY.register("poplar_sapling", PoplarSaplingBlock::new);
	public static final DeferredBlock<Block> COLD_DESERT_GRASS = REGISTRY.register("cold_desert_grass", ColdDesertGrassBlock::new);
	public static final DeferredBlock<Block> CAMELTHORN = REGISTRY.register("camelthorn", CamelthornBlock::new);
	public static final DeferredBlock<Block> COLD_DESERT_DIRT = REGISTRY.register("cold_desert_dirt", ColdDesertDirtBlock::new);
	public static final DeferredBlock<Block> BAOBAB_WOOD = REGISTRY.register("baobab_wood", BaobabWoodBlock::new);
	public static final DeferredBlock<Block> BAOBAB_LOG = REGISTRY.register("baobab_log", BaobabLogBlock::new);
	public static final DeferredBlock<Block> BAOBAB_PLANKS = REGISTRY.register("baobab_planks", BaobabPlanksBlock::new);
	public static final DeferredBlock<Block> BAOBAB_LEAVES = REGISTRY.register("baobab_leaves", BaobabLeavesBlock::new);
	public static final DeferredBlock<Block> BAOBAB_STAIRS = REGISTRY.register("baobab_stairs", BaobabStairsBlock::new);
	public static final DeferredBlock<Block> BAOBAB_SLAB = REGISTRY.register("baobab_slab", BaobabSlabBlock::new);
	public static final DeferredBlock<Block> BAOBAB_FENCE = REGISTRY.register("baobab_fence", BaobabFenceBlock::new);
	public static final DeferredBlock<Block> BAOBAB_FENCE_GATE = REGISTRY.register("baobab_fence_gate", BaobabFenceGateBlock::new);
	public static final DeferredBlock<Block> BAOBAB_PRESSURE_PLATE = REGISTRY.register("baobab_pressure_plate", BaobabPressurePlateBlock::new);
	public static final DeferredBlock<Block> BAOBAB_BUTTON = REGISTRY.register("baobab_button", BaobabButtonBlock::new);
	public static final DeferredBlock<Block> BAOBAB_DOOR = REGISTRY.register("baobab_door", BaobabDoorBlock::new);
	public static final DeferredBlock<Block> BAOBAB_TRAPDOOR = REGISTRY.register("baobab_trapdoor", BaobabTrapdoorBlock::new);
	public static final DeferredBlock<Block> STRIPPED_BAOBAB_WOOD = REGISTRY.register("stripped_baobab_wood", StrippedBaobabWoodBlock::new);
	public static final DeferredBlock<Block> STRIPPED_BAOBAB_LOG = REGISTRY.register("stripped_baobab_log", StrippedBaobabLogBlock::new);
	public static final DeferredBlock<Block> BAOBAB_SAPLING = REGISTRY.register("baobab_sapling", BaobabSaplingBlock::new);
	public static final DeferredBlock<Block> ANTHILL = REGISTRY.register("anthill", AnthillBlock::new);
	public static final DeferredBlock<Block> FORMICARIUM = REGISTRY.register("formicarium", FormicariumBlock::new);
	public static final DeferredBlock<Block> MAPLE_WOOD = REGISTRY.register("maple_wood", MapleWoodBlock::new);
	public static final DeferredBlock<Block> MAPLE_LOG = REGISTRY.register("maple_log", MapleLogBlock::new);
	public static final DeferredBlock<Block> MAPLE_PLANKS = REGISTRY.register("maple_planks", MaplePlanksBlock::new);
	public static final DeferredBlock<Block> MAPLE_LEAVES = REGISTRY.register("maple_leaves", MapleLeavesBlock::new);
	public static final DeferredBlock<Block> MAPLE_STAIRS = REGISTRY.register("maple_stairs", MapleStairsBlock::new);
	public static final DeferredBlock<Block> MAPLE_SLAB = REGISTRY.register("maple_slab", MapleSlabBlock::new);
	public static final DeferredBlock<Block> MAPLE_FENCE = REGISTRY.register("maple_fence", MapleFenceBlock::new);
	public static final DeferredBlock<Block> MAPLE_FENCE_GATE = REGISTRY.register("maple_fence_gate", MapleFenceGateBlock::new);
	public static final DeferredBlock<Block> MAPLE_PRESSURE_PLATE = REGISTRY.register("maple_pressure_plate", MaplePressurePlateBlock::new);
	public static final DeferredBlock<Block> MAPLE_BUTTON = REGISTRY.register("maple_button", MapleButtonBlock::new);
	public static final DeferredBlock<Block> STRIPPED_MAPLE_LOG = REGISTRY.register("stripped_maple_log", StrippedMapleLogBlock::new);
	public static final DeferredBlock<Block> STRIPPED_MAPLE_WOOD = REGISTRY.register("stripped_maple_wood", StrippedMapleWoodBlock::new);
	public static final DeferredBlock<Block> MAPLE_DOOR = REGISTRY.register("maple_door", MapleDoorBlock::new);
	public static final DeferredBlock<Block> MAPLE_TRAPDOOR = REGISTRY.register("maple_trapdoor", MapleTrapdoorBlock::new);
	public static final DeferredBlock<Block> MAPLE_SAPLING = REGISTRY.register("maple_sapling", MapleSaplingBlock::new);
	public static final DeferredBlock<Block> SAPPY_MAPLE_LOG = REGISTRY.register("sappy_maple_log", SappyMapleLogBlock::new);
	public static final DeferredBlock<Block> SAPPY_MAPLE_WOOD = REGISTRY.register("sappy_maple_wood", SappyMapleWoodBlock::new);
	public static final DeferredBlock<Block> BEECH_WOOD = REGISTRY.register("beech_wood", BeechWoodBlock::new);
	public static final DeferredBlock<Block> BEECH_LOG = REGISTRY.register("beech_log", BeechLogBlock::new);
	public static final DeferredBlock<Block> BEECH_PLANKS = REGISTRY.register("beech_planks", BeechPlanksBlock::new);
	public static final DeferredBlock<Block> BEECH_LEAVES = REGISTRY.register("beech_leaves", BeechLeavesBlock::new);
	public static final DeferredBlock<Block> BEECH_STAIRS = REGISTRY.register("beech_stairs", BeechStairsBlock::new);
	public static final DeferredBlock<Block> BEECH_SLAB = REGISTRY.register("beech_slab", BeechSlabBlock::new);
	public static final DeferredBlock<Block> BEECH_FENCE = REGISTRY.register("beech_fence", BeechFenceBlock::new);
	public static final DeferredBlock<Block> BEECH_FENCE_GATE = REGISTRY.register("beech_fence_gate", BeechFenceGateBlock::new);
	public static final DeferredBlock<Block> BEECH_PRESSURE_PLATE = REGISTRY.register("beech_pressure_plate", BeechPressurePlateBlock::new);
	public static final DeferredBlock<Block> BEECH_BUTTON = REGISTRY.register("beech_button", BeechButtonBlock::new);
	public static final DeferredBlock<Block> STRIPPED_BEECH_WOOD = REGISTRY.register("stripped_beech_wood", StrippedBeechWoodBlock::new);
	public static final DeferredBlock<Block> STRIPPED_BEECH_LOG = REGISTRY.register("stripped_beech_log", StrippedBeechLogBlock::new);
	public static final DeferredBlock<Block> BEECH_DOOR = REGISTRY.register("beech_door", BeechDoorBlock::new);
	public static final DeferredBlock<Block> BEECH_TRAPDOOR = REGISTRY.register("beech_trapdoor", BeechTrapdoorBlock::new);
	public static final DeferredBlock<Block> PALM_WOOD = REGISTRY.register("palm_wood", PalmWoodBlock::new);
	public static final DeferredBlock<Block> PALM_LOG = REGISTRY.register("palm_log", PalmLogBlock::new);
	public static final DeferredBlock<Block> PALM_PLANKS = REGISTRY.register("palm_planks", PalmPlanksBlock::new);
	public static final DeferredBlock<Block> PALM_LEAVES = REGISTRY.register("palm_leaves", PalmLeavesBlock::new);
	public static final DeferredBlock<Block> PALM_STAIRS = REGISTRY.register("palm_stairs", PalmStairsBlock::new);
	public static final DeferredBlock<Block> PALM_SLAB = REGISTRY.register("palm_slab", PalmSlabBlock::new);
	public static final DeferredBlock<Block> PALM_FENCE = REGISTRY.register("palm_fence", PalmFenceBlock::new);
	public static final DeferredBlock<Block> PALM_FENCE_GATE = REGISTRY.register("palm_fence_gate", PalmFenceGateBlock::new);
	public static final DeferredBlock<Block> PALM_PRESSURE_PLATE = REGISTRY.register("palm_pressure_plate", PalmPressurePlateBlock::new);
	public static final DeferredBlock<Block> PALM_BUTTON = REGISTRY.register("palm_button", PalmButtonBlock::new);
	public static final DeferredBlock<Block> STRIPPED_PALM_WOOD = REGISTRY.register("stripped_palm_wood", StrippedPalmWoodBlock::new);
	public static final DeferredBlock<Block> STRIPPED_PALM_LOG = REGISTRY.register("stripped_palm_log", StrippedPalmLogBlock::new);
	public static final DeferredBlock<Block> PALM_DOOR = REGISTRY.register("palm_door", PalmDoorBlock::new);
	public static final DeferredBlock<Block> PALM_TRAPDOOR = REGISTRY.register("palm_trapdoor", PalmTrapdoorBlock::new);
	public static final DeferredBlock<Block> PALM_SAPLING = REGISTRY.register("palm_sapling", PalmSaplingBlock::new);
	public static final DeferredBlock<Block> BEECH_SAPLING = REGISTRY.register("beech_sapling", BeechSaplingBlock::new);
	public static final DeferredBlock<Block> ASPEN_WOOD = REGISTRY.register("aspen_wood", AspenWoodBlock::new);
	public static final DeferredBlock<Block> ASPEN_LOG = REGISTRY.register("aspen_log", AspenLogBlock::new);
	public static final DeferredBlock<Block> ASPEN_PLANKS = REGISTRY.register("aspen_planks", AspenPlanksBlock::new);
	public static final DeferredBlock<Block> ASPEN_LEAVES = REGISTRY.register("aspen_leaves", AspenLeavesBlock::new);
	public static final DeferredBlock<Block> ASPEN_STAIRS = REGISTRY.register("aspen_stairs", AspenStairsBlock::new);
	public static final DeferredBlock<Block> ASPEN_SLAB = REGISTRY.register("aspen_slab", AspenSlabBlock::new);
	public static final DeferredBlock<Block> ASPEN_FENCE = REGISTRY.register("aspen_fence", AspenFenceBlock::new);
	public static final DeferredBlock<Block> ASPEN_FENCE_GATE = REGISTRY.register("aspen_fence_gate", AspenFenceGateBlock::new);
	public static final DeferredBlock<Block> ASPEN_PRESSURE_PLATE = REGISTRY.register("aspen_pressure_plate", AspenPressurePlateBlock::new);
	public static final DeferredBlock<Block> ASPEN_BUTTON = REGISTRY.register("aspen_button", AspenButtonBlock::new);
	public static final DeferredBlock<Block> ASPEN_SAPLING = REGISTRY.register("aspen_sapling", AspenSaplingBlock::new);
	public static final DeferredBlock<Block> STRIPPED_ASPEN_WOOD = REGISTRY.register("stripped_aspen_wood", StrippedAspenWoodBlock::new);
	public static final DeferredBlock<Block> STRIPPED_ASPEN_LOG = REGISTRY.register("stripped_aspen_log", StrippedAspenLogBlock::new);
	public static final DeferredBlock<Block> ASPEN_DOOR = REGISTRY.register("aspen_door", AspenDoorBlock::new);
	public static final DeferredBlock<Block> ASPEN_TRAPDOOR = REGISTRY.register("aspen_trapdoor", AspenTrapdoorBlock::new);
	public static final DeferredBlock<Block> GINKGO_WOOD = REGISTRY.register("ginkgo_wood", GinkgoWoodBlock::new);
	public static final DeferredBlock<Block> GINKGO_LOG = REGISTRY.register("ginkgo_log", GinkgoLogBlock::new);
	public static final DeferredBlock<Block> GINKGO_PLANKS = REGISTRY.register("ginkgo_planks", GinkgoPlanksBlock::new);
	public static final DeferredBlock<Block> GINKGO_LEAVES = REGISTRY.register("ginkgo_leaves", GinkgoLeavesBlock::new);
	public static final DeferredBlock<Block> GINKGO_STAIRS = REGISTRY.register("ginkgo_stairs", GinkgoStairsBlock::new);
	public static final DeferredBlock<Block> GINKGO_SLAB = REGISTRY.register("ginkgo_slab", GinkgoSlabBlock::new);
	public static final DeferredBlock<Block> GINKGO_FENCE = REGISTRY.register("ginkgo_fence", GinkgoFenceBlock::new);
	public static final DeferredBlock<Block> GINKGO_FENCE_GATE = REGISTRY.register("ginkgo_fence_gate", GinkgoFenceGateBlock::new);
	public static final DeferredBlock<Block> GINKGO_PRESSURE_PLATE = REGISTRY.register("ginkgo_pressure_plate", GinkgoPressurePlateBlock::new);
	public static final DeferredBlock<Block> GINKGO_BUTTON = REGISTRY.register("ginkgo_button", GinkgoButtonBlock::new);
	public static final DeferredBlock<Block> STRIPPED_GINKGO_WOOD = REGISTRY.register("stripped_ginkgo_wood", StrippedGinkgoWoodBlock::new);
	public static final DeferredBlock<Block> STRIPPED_GINKGO_LOG = REGISTRY.register("stripped_ginkgo_log", StrippedGinkgoLogBlock::new);
	public static final DeferredBlock<Block> GINKGO_DOOR = REGISTRY.register("ginkgo_door", GinkgoDoorBlock::new);
	public static final DeferredBlock<Block> GINKGO_TRAPDOOR = REGISTRY.register("ginkgo_trapdoor", GinkgoTrapdoorBlock::new);
	public static final DeferredBlock<Block> GINKGO_SAPLING = REGISTRY.register("ginkgo_sapling", GinkgoSaplingBlock::new);
	public static final DeferredBlock<Block> EUCALYPTUS_WOOD = REGISTRY.register("eucalyptus_wood", EucalyptusWoodBlock::new);
	public static final DeferredBlock<Block> EUCALYPTUS_LOG = REGISTRY.register("eucalyptus_log", EucalyptusLogBlock::new);
	public static final DeferredBlock<Block> EUCALYPTUS_PLANKS = REGISTRY.register("eucalyptus_planks", EucalyptusPlanksBlock::new);
	public static final DeferredBlock<Block> EUCALYPTUS_LEAVES = REGISTRY.register("eucalyptus_leaves", EucalyptusLeavesBlock::new);
	public static final DeferredBlock<Block> EUCALYPTUS_STAIRS = REGISTRY.register("eucalyptus_stairs", EucalyptusStairsBlock::new);
	public static final DeferredBlock<Block> EUCALYPTUS_SLAB = REGISTRY.register("eucalyptus_slab", EucalyptusSlabBlock::new);
	public static final DeferredBlock<Block> EUCALYPTUS_FENCE = REGISTRY.register("eucalyptus_fence", EucalyptusFenceBlock::new);
	public static final DeferredBlock<Block> EUCALYPTUS_FENCE_GATE = REGISTRY.register("eucalyptus_fence_gate", EucalyptusFenceGateBlock::new);
	public static final DeferredBlock<Block> EUCALYPTUS_PRESSURE_PLATE = REGISTRY.register("eucalyptus_pressure_plate", EucalyptusPressurePlateBlock::new);
	public static final DeferredBlock<Block> EUCALYPTUS_BUTTON = REGISTRY.register("eucalyptus_button", EucalyptusButtonBlock::new);
	public static final DeferredBlock<Block> STRIPPED_EUCALYPTUS_WOOD = REGISTRY.register("stripped_eucalyptus_wood", StrippedEucalyptusWoodBlock::new);
	public static final DeferredBlock<Block> STRIPPED_EUCALYPTUS_LOG = REGISTRY.register("stripped_eucalyptus_log", StrippedEucalyptusLogBlock::new);
	public static final DeferredBlock<Block> EUCALYPTUS_DOOR = REGISTRY.register("eucalyptus_door", EucalyptusDoorBlock::new);
	public static final DeferredBlock<Block> EUCALYPTUS_TRAPDOOR = REGISTRY.register("eucalyptus_trapdoor", EucalyptusTrapdoorBlock::new);
	public static final DeferredBlock<Block> EUCALYPTUS_SAPLING = REGISTRY.register("eucalyptus_sapling", EucalyptusSaplingBlock::new);
	public static final DeferredBlock<Block> SILVER_ORE = REGISTRY.register("silver_ore", SilverOreBlock::new);
	public static final DeferredBlock<Block> SILVER_BLOCK = REGISTRY.register("silver_block", SilverBlockBlock::new);
	public static final DeferredBlock<Block> DEEPSLATE_SILVER_ORE = REGISTRY.register("deepslate_silver_ore", DeepslateSilverOreBlock::new);
	public static final DeferredBlock<Block> RAW_SILVER_BLOCK = REGISTRY.register("raw_silver_block", RawSilverBlockBlock::new);
	public static final DeferredBlock<Block> COCONUT_BLOCK = REGISTRY.register("coconut_block", CoconutBlockBlock::new);
	public static final DeferredBlock<Block> COBALT_ORE = REGISTRY.register("cobalt_ore", CobaltOreBlock::new);
	public static final DeferredBlock<Block> COBALT_BLOCK = REGISTRY.register("cobalt_block", CobaltBlockBlock::new);
	public static final DeferredBlock<Block> DEEPSLATE_COBALT_ORE = REGISTRY.register("deepslate_cobalt_ore", DeepslateCobaltOreBlock::new);
	public static final DeferredBlock<Block> REGULAR_BUSH = REGISTRY.register("regular_bush", RegularBushBlock::new);
	public static final DeferredBlock<Block> LAVENDER = REGISTRY.register("lavender", LavenderBlock::new);
	public static final DeferredBlock<Block> DAFFODIL = REGISTRY.register("daffodil", DaffodilBlock::new);
	public static final DeferredBlock<Block> QUICKSAND = REGISTRY.register("quicksand", QuicksandBlock::new);

	// Start of user code block custom blocks
	// End of user code block custom blocks
	@EventBusSubscriber(bus = EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class BlocksClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.Block event) {
			HornbeamLeavesBlock.blockColorLoad(event);
			LindenLeavesBlock.blockColorLoad(event);
			WillowLeavesBlock.blockColorLoad(event);
			OutbackBushBlock.blockColorLoad(event);
			PoplarLeavesBlock.blockColorLoad(event);
			BaobabLeavesBlock.blockColorLoad(event);
			MapleLeavesBlock.blockColorLoad(event);
			BeechLeavesBlock.blockColorLoad(event);
			PalmLeavesBlock.blockColorLoad(event);
			GinkgoLeavesBlock.blockColorLoad(event);
			EucalyptusLeavesBlock.blockColorLoad(event);
			RegularBushBlock.blockColorLoad(event);
		}

		@SubscribeEvent
		public static void itemColorLoad(RegisterColorHandlersEvent.Item event) {
			HornbeamLeavesBlock.itemColorLoad(event);
			LindenLeavesBlock.itemColorLoad(event);
			WillowLeavesBlock.itemColorLoad(event);
			OutbackBushBlock.itemColorLoad(event);
			PoplarLeavesBlock.itemColorLoad(event);
			BaobabLeavesBlock.itemColorLoad(event);
			MapleLeavesBlock.itemColorLoad(event);
			BeechLeavesBlock.itemColorLoad(event);
			PalmLeavesBlock.itemColorLoad(event);
			GinkgoLeavesBlock.itemColorLoad(event);
			EucalyptusLeavesBlock.itemColorLoad(event);
			RegularBushBlock.itemColorLoad(event);
		}
	}
}
